from sf_utils.version_helper import get_app_version


class AppStrings:
    """
    애플리케이션에서 사용하는 모든 사용자 인터페이스 문자열 및 로그/에러 메시지를 관리하는 클래스입니다.
    가독성과 유지보수성을 위해 카테고리별로 그룹화되어 있습니다.
    """

    # =========================================================================
    # [1] 기본 앱 정보 (Basic App Info)
    # =========================================================================
    APP_TITLE = "StringFinder"
    APP_VERSION = get_app_version()  # pyproject.toml 기반 Single Source
    APP_AUTHOR = "Antigravity"
    TITLE_CRITICAL_ERROR = "StringFinder Error"
    TITLE_QT_WARNING = "QThread Warning"
    STATUS_ELAPSED_TIME = "소요 시간: {:02d}:{:02d}"
    MSG_SEARCH_SINGLE_CHAR_WARN = "검색어가 너무 짧아 검색 시간이 오래 걸릴 수 있습니다. 진행하시겠습니까?"
    MSG_ALREADY_RUNNING = "프로그램이 이미 실행 중입니다."
    # =========================================================================
    # [2] UI 요소 (Buttons, Menus, Labels)
    # =========================================================================
    SEARCH_LABEL = "문자열 검색"
    ADD_TAB_BTN = "+"
    ADD_FOLDER_BTN = "폴더 추가"
    ADD_EXT_BTN = "추가"
    SELECT_ALL_BTN = "전체 선택"
    DESELECT_ALL_BTN = "전체 해제"
    BTN_CLOSE = "닫기"
    SEARCH_BTN = "검색"
    SEARCH_BTN_STOP = "중지"
    SEARCH_BTN_STOPPING = "중지 중..."
    OPEN_FILE = "파일 열기"
    OPEN_FOLDER = "폴더 열기"
    COPY_PATH = "경로 복사 (Ctrl+C)"
    COPY_CONTENT = "내용 복사 (Ctrl+C)"
    FILENAME_FILTER_LABEL = "파일명 필터:"
    SELECT_FOLDER_TITLE = "폴더 선택"
    PAGINATION_PREV = "이전"
    PAGINATION_NEXT = "다음"
    PAGINATION_PAGE = "페이지:"
    PAGINATION_OF = "/"
    PAGINATION_DISPLAY = "표시:"
    PAGINATION_SIZE_1000 = "1000"
    PAGINATION_SIZE_2000 = "2000"
    PAGINATION_SIZE_5000 = "5000"
    SUCCESS_TITLE = "성공"
    INFO_TITLE = "알림"
    INFO_CLEAR_SUCCESS = "데이터가 성공적으로 삭제되었습니다."
    INFO_RESET_LAYOUT_DONE = "레이아웃이 초기화되었습니다."
    INFO_LOGS_DELETED = "로그가 삭제되었습니다."
    HISTORY_CLEAR_ALL = "--- 기록 삭제 ---"
    DOCK_SEARCH_TITLE = "검색 설정"
    DOCK_FOLDER_TITLE = "폴더 목록(하위 폴더 포함)"
    DOCK_EXT_TITLE = "확장자 목록"
    DOCK_FILENAME_TITLE = "파일명 필터"
    DOCK_RESULT_TITLE = "검색 결과"
    MENU_LOCK_LAYOUT = "레이아웃 잠금"
    MENU_RESET_LAYOUT = "레이아웃 초기화"
    TAB_RENAME_TITLE = "탭 이름 변경"
    TAB_RENAME_PROMPT = "새 탭 이름을 입력하세요:"
    TAB_CLOSE_MENU = "탭 닫기"
    SEARCH_TAB_DEFAULT_TITLE = "검색"
    SEARCH_TAB_TITLE_TEMPLATE = "{} {}"
    TAB_RESULTS = "검색 결과"
    TAB_LOGS = "로그"
    SETTINGS_TITLE = "설정"
    SETTINGS_GROUP_GENERAL = "일반"
    SETTINGS_GROUP_APPEARANCE = "화면"
    SETTINGS_GROUP_LOG = "로그"
    SETTINGS_GROUP_DATA = "데이터"
    THEME_LABEL = "테마:"
    THEME_DARK = "다크"
    THEME_LIGHT = "라이트"
    LOG_RETENTION_LABEL = "로그 보관:"
    BTN_DELETE_ALL_LOGS = "모든 로그 삭제"
    MSG_DELETE_LOGS_CONFIRM = "모든 로그 파일을 삭제하시겠습니까?"
    MAX_FILES_LABEL = "최대 파일 수:"
    MAX_DAYS_LABEL = "최대 보관 일수:"
    OPEN_DATA_DIR_BTN = "데이터 폴더 열기"
    CLEAR_ALL_DATA_BTN = "모든 데이터 삭제"
    CLEAR_ALL_DATA_CONFIRM = "모든 설정과 기록을 삭제하시겠습니까?"
    COMBO_ENABLE = "사용"
    COMBO_DISABLE = "사용 안 함"
    COMBO_LOCKED = "잠금"
    COMBO_UNLOCKED = "해제"
    # =========================================================================
    # [3] 도움말 및 툴팁 (Tooltips & Guidance)
    # =========================================================================
    COMPLEX_SEARCH_LABEL = " (느림)"
    COMPLEX_SEARCH_TOOLTIP = (
        "영어, 한글, 일반 특수 문자가 아닌 경우까지 검색 합니다.\n"
        "예: 독일어(ß↔ss), 프랑스어(Œ↔oe), 원문자(㉮↔가) 및 복잡한 유니코드 변형\n"
        "정밀 하게 검사하는 대신, 속도가 느립니다."
    )
    EXCLUDE_HIDDEN_LABEL = "시스템 항목 제외"
    EXCLUDE_HIDDEN_TOOLTIP = (
        "윈도우의 '숨김' 속성이 설정된 폴더와 파일을 검색에서 제외합니다.\n"
        ".git, node_modules, AppData 등 불필요한 스캔을 줄여 속도가 대폭 향상됩니다."
    )
    EXCLUDE_BINARY_LABEL = "바이너리 파일 제외"
    EXCLUDE_BINARY_TOOLTIP = (
        "이미지, 실행 파일(exe, dll) 등 바이너리 파일을 검색 대상에서 제외합니다.\n"
        "항상 검색이 필요한 특수 모드(Excel 등)나 직접 지정한 확장자는 제외 대상에서 보호됩니다."
    )
    BOOLEAN_SEARCH_LABEL = "존재 여부만 확인 (고속)"
    BOOLEAN_SEARCH_TOOLTIP = (
        "파일 내에 해당 텍스트가 존재하는지만 빠르게 확인합니다.\n"
        "첫 번째 일치 항목을 찾으면 즉시 다음 파일로 넘어가므로 매우 빠릅니다.\n"
        "상세 매치(줄 번호 등)는 제공되지 않습니다."
    )
    SPECIAL_SEARCH_LABEL = "특수 검색:"
    SPECIAL_SEARCH_OFF = "끄기"
    SPECIAL_SEARCH_ITEMS = [
        "끄기",
        "XML (부분 일치)",
        "XML (정확히 일치)",
        "JSON (부분 일치)",
        "JSON (정확히 일치)",
        "Archive (부분 일치)",
        "Archive (정확히 일치)",
        "Excel (부분 일치)",
        "Excel (정확히 일치)",
    ]
    SPECIAL_SEARCH_XML = "XML (부분 일치)"
    SPECIAL_SEARCH_JSON = "JSON (부분 일치)"
    SPECIAL_SEARCH_ARCHIVE = "Archive (부분 일치)"
    SPECIAL_SEARCH_EXCEL = "Excel (부분 일치)"
    # =========================================================================
    # [4] 입력 필드 및 플레이스홀더 (Placeholders)
    # =========================================================================
    SEARCH_EDIT_PLACEHOLDER = (
        "검색할 문자열 입력...(검색을 원하는 문자열이 '한글', '영어', '일반 특수 문자'가 아닌 경우. 정밀 검색 사용)"
    )
    EXT_EDIT_PLACEHOLDER = "확장자 (예: txt)"
    FILENAME_EDIT_PLACEHOLDER = "파일명 필터 (예: npc, fo / 콤마 구분)..."
    FILENAME_LIST_PLACEHOLDER = "필터 단어 (예: npc)"
    RESULT_FILTER_FILE_PLACEHOLDER = "파일 필터..."
    RESULT_FILTER_FOLDER_PLACEHOLDER = "폴더 필터..."
    MATCH_FILTER_LIST_PLACEHOLDER = "목록 필터..."
    MATCH_FILTER_LINE_PLACEHOLDER = "라인 필터..."
    MATCH_FILTER_CONTENT_PLACEHOLDER = "내용 필터..."
    MATCH_FILTER_NAME_PLACEHOLDER = "이름 필터..."
    MATCH_FILTER_KEY_PLACEHOLDER = "키 필터..."
    MATCH_FILTER_VALUE_PLACEHOLDER = "값 필터..."
    MATCH_FILTER_ARCHIVE_NS_PLACEHOLDER = "네임스페이스 필터..."
    MATCH_FILTER_ARCHIVE_KEY_PLACEHOLDER = "키 필터..."
    MATCH_FILTER_ARCHIVE_SOURCE_PLACEHOLDER = "소스 필터..."
    MATCH_FILTER_ARCHIVE_TRANS_PLACEHOLDER = "번역 필터..."
    MATCH_FILTER_EXCEL_SHEET_PLACEHOLDER = "시트 필터..."
    MATCH_FILTER_EXCEL_CELL_PLACEHOLDER = "셀 필터..."
    MATCH_FILTER_EXCEL_VAL_PLACEHOLDER = "값 필터..."
    # =========================================================================
    # [5] 테이블 헤더 (Table Headers)
    # =========================================================================
    HEADER_COUNT = "개수"
    HEADER_FOLDER = "폴더"
    HEADER_FILE = "파일"
    HEADER_POSITION = "위치"
    HEADER_CONTENT = "내용"
    HEADER_JSON_KEY = "키"
    HEADER_JSON_VALUE = "값"
    HEADER_XML_NAME = "키"  # 이름에서 키로 변경
    HEADER_XML_VALUE = "값"
    HEADER_ARCHIVE_NAMESPACE = "네임스페이스"
    HEADER_ARCHIVE_KEY = "키"
    HEADER_ARCHIVE_SOURCE = "소스"
    HEADER_ARCHIVE_TRANSLATION = "번역"
    HEADER_EXCEL_SHEET = "시트"
    HEADER_EXCEL_CELL = "셀"
    HEADER_EXCEL_VALUE = "값"
    HEADER_LIST = "목록"
    # =========================================================================
    # [6] 상태 및 결과 메시지 (Status & Results)
    # =========================================================================
    STATUS_READY = "준비"
    STATUS_IDLE = "대기형"
    STATUS_SCANNING = "파일 스캔 중..."
    STATUS_SEARCHING = "문자열 검색 중..."
    STATUS_STOPPING = "중지 중..."
    STATUS_FOUND_COUNT = "{}개 파일에서 검색 완료"
    STATUS_ERROR_PREFIX = "[오류] "
    RESULT_SUMMARY_TEMPLATE = "발견: {}개 파일 | 매치: {}개"
    RESULT_EMPTY_MSG = "검색을 시작 해주세요."
    RESULT_SEARCHING_MSG = '"{}" 검색 중 입니다.'
    RESULT_EMPTY_NO_FOLDER = "검색할 폴더를 추가해주세요."
    RESULT_EMPTY_NO_MATCH = "'{}'에 대한 검색 결과가 없습니다. 누락된 문자열이 있을 경우 정밀 검색을 사용해주세요."
    RESULT_SUMMARY_FORMAT = "문자열 포함 파일 수 : {file_count} | 전체 매칭된 문자열의 수 : {match_count} | 건너뛴 파일 수 : {skip_count} | 시간 : {duration}s"
    SUMMARY_PREFIX_SEARCHING = "[검색 중] "
    SUMMARY_PREFIX_STOPPED = "[검색 중지] "
    SUMMARY_PREFIX_FINISHED = "[검색 완료] "
    RESULT_MSG_SKIPPED_DETAILS = "{}개의 매치가 발견되었습니다. ({}개 파일 스킵: {}...)"
    RESULT_MSG_SKIPPED_SIMPLE = "{}개의 매치가 발견되었습니다. ({}개 파일 스킵)"
    MSG_LOG_LIMIT_REACHED = "[안내] 로그 표시 제한(5,000줄)에 도달하여 이전 로그를 정리했습니다."
    MSG_MATCH_TRUNCATION_NOTICE = "(검색 결과가 너무 많아 일부 상세 매치가 제한되었습니다)"
    MSG_BINARY_FILE = "[이진 파일]"
    MSG_BINARY_MATCH = "[이진 파일에서 {}개 항목 발견]"
    MSG_LONG_LINE_PREVIEW = "{}... (긴 줄)"
    SKIP_EMPTY_FILE = "빈 파일"
    SEARCH_MODE_EXACT = "정확히 일치"
    SEARCH_MODE_COMPLEX = "정밀 검색"
    BOOLEAN_SEARCH_MATCH_CONTENT = "[파일 내 일치하는 항목 존재]"
    # =========================================================================
    # [7] 내보내기 (Export)
    # =========================================================================
    RESULT_EXPORT_TITLE = "결과 내보내기"
    RESULT_EXPORT_FILTER = "엑셀 파일 (*.xlsx);;텍스트 파일 (*.txt)"
    RESULT_EXPORT_ALL = "전체 내보내기"
    EXPORT_TEXT_HEADER = "--- StringFinder 검색 결과 ---"
    EXPORT_TEXT_SEPARATOR = "-" * 80
    EXPORT_TEXT_LINE_PREFIX = "라인 {}: {}"
    EXPORT_SUMMARY_PREFIX = "요약: "
    EXCEL_SHEET_FILE_LIST = "검색 파일 목록"
    EXCEL_SHEET_MATCH_DETAILS = "검색 상세"
    HEADER_MATCH_COUNT = "매치 수"
    # =========================================================================
    # [8] 시스템 로그 (System Logs) - 형식: [시스템] 메시지
    # =========================================================================
    LOG_SYS_APP_STARTED_DECO = "--- 앱 시작 ---"
    LOG_SYS_SINGLE_INSTANCE_DETECTED = "[시스템] 이미 실행 중인 인스턴스가 발견되었습니다. 기존 창을 활성화합니다."
    LOG_SYS_SINGLE_INSTANCE_SERVER_START = "[시스템] 단일 인스턴스 서버 시작: {}"
    LOG_SYS_SINGLE_INSTANCE_SERVER_START_FAIL = "[시스템] 단일 인스턴스 서버 시작 실패: {}"
    LOG_SYS_SINGLE_INSTANCE_REQUEST = "[시스템] 중복 실행 요청 감지 - 기존 창 활성화"
    LOG_SYS_SHUTDOWN = "[시스템] 종료 중..."
    LOG_SYS_LOG_CLEANUP_DONE = "[시스템] 로그 파일 {}개 정리 완료."
    LOG_SYS_RUST_SUCCESS = "[시스템] Rust 엔진 로드됨."
    LOG_SYS_RUST_FALLBACK = "[시스템] Rust 엔진 로드 실패. [Python 대체 환경]으로 구동합니다."
    LOG_SYS_RUST_RUNTIME_FALLBACK = "[엔진] Rust 오류로 인해 자동으로 Python 엔진으로 대체합니다."
    LOG_SYS_SMART_SCAN_FALLBACK = "[스캔] 스마트 스캔 오류가 발견되어 Python 스캔으로 전환합니다."
    LOG_SYS_WKR_SHUTDOWN = "[시스템] 워커 프로세스 종료 중..."
    LOG_SYS_WKR_SHUTDOWN_DONE = "[시스템] 워커 프로세스 종료 완료"
    LOG_SYS_WKR_SHUTDOWN_FAIL = "[시스템] 워커 프로세스 종료 실패: {}"
    LOG_SYS_SF_ENGINE_NOT_FOUND = "[시스템] 경고: Rust 엔진 라이브러리를 찾을 수 없음: {}"
    LOG_SYS_LOG_DIR_TEMP = "[시스템] 경고: AppData에 로그 디렉토리를 생성하지 못해 임시 폴더를 사용합니다: {}"
    LOG_SYS_UNCAUGHT_EXCEPTION = "[시스템] 처리되지 않은 예외 발생"
    LOG_SYS_SCAN_WORKER_BROKEN = "[시스템] 스캔 워커가 손상되었습니다 (None)."
    LOG_SYS_QT_THREAD_WARNING = "[시스템] QThread 경고 감지: {}\n스택 트레이스:\n{}"
    LOG_SYS_CLI_ARGS_PARSE_FAIL = "[시스템] 인수 파싱 예외 발생: {}"
    LOG_SYS_DATA_DIR_CHECK_FAIL = "[시스템] 데이터 폴더 접근 실패: {}"
    LOG_SYS_CLEANUP_SKIP = "[시스템] 로그 정리 건너뜀 ({}): {}"
    LOG_SYS_CLEANUP_ERROR = "[시스템] 종료 정리 중 오류: {}"
    MSG_RUST_LOAD_FAIL = "[시스템] Rust 엔진 로드 실패."
    MSG_RUST_LOAD_FAIL_GUIDE = (
        "Rust 엔진을 로드할 수 없습니다.\n\n"
        "해결 방법:\n"
        "1. Microsoft Visual C++ 재배포 가능 패키지(x64)를 설치하세요.\n"
        "2. 백신 프로그램이 sf_engine.pyd 파일을 차단하고 있는지 확인하세요."
    )
    MSG_QT_THREAD_DESTROYED = "[시스템] 스레드가 종료되기 전에 파괴되었습니다."
    MSG_QT_RESOURCE_LEAK = "[시스템] 프로그램 종료 시 리소스가 정상적으로 해제되지 않았을 수 있습니다."
    MSG_CRITICAL_ERROR_POPUP = (
        "[시스템] 치명적인 오류가 발생했습니다:\n\n{}\n\n상세 내용은 crash_dump.txt를 확인하세요."
    )
    LOG_SYS_CRITICAL_STOP_ALL = "[시스템] 치명적 오류 감지로 인해 모든 검색 작업을 강제 중지합니다."
    LOG_SYS_TAB_STOP_FAIL = "[시스템] 탭 중지 실패: {}"
    LOG_SYS_MEMORY_WARNING = "[시스템] {} (현재: {}%)"
    LOG_SYS_MEMORY_CHECK_FAIL = "[시스템] 메모리 확인 실패: {}"
    LOG_SYS_RUST_FAIL_MSG_UI_MISSING = "[UI] Rust 로드 실패 메시지 표시 중 UI 객체 유실: {}"
    LOG_SYS_NO_TABS_TO_REMOVE = "[UI] 현재 닫을 수 있는 활성 탭이 없습니다."
    LOG_SYS_CLEANUP_SIGNALER_FAIL = "[UI] 로그 신호기 연결 해제 실패: {}"
    LOG_SYS_CLEANUP_DEFERRED = "[UI] 시스템 매니저 정리 작업 지연됨"
    LOG_SYS_SINGLE_INSTANCE_LOCK_SUCCESS = "[시스템] 단일 인스턴스 락 획득 완료: {}"
    # =========================================================================
    # [9] 설정 로그 (Config Logs) - 형식: [설정] 메시지
    # =========================================================================
    LOG_CFG_LOAD_FAIL = "[설정] 로드 실패, 기본값 사용: {}"
    LOG_CFG_READ_ERROR = "[설정] 읽기 오류: {}"
    LOG_CFG_SAVE_FAIL = "[설정] 저장 실패: {}"
    LOG_CFG_SAVE_SHUTDOWN_FAIL = "[설정] 종료 시 최종 설정 저장 실패"
    LOG_CFG_SAVED = "[설정] 설정 파일이 저장되었습니다: {}"
    LOG_CFG_SAVE_ERROR = "[설정] 설정 파일 저장 중 오류 발생: {} ({})"
    LOG_CFG_SAVE_RETRY = "[설정] 저장 재시도 {} 실패: {}"
    LOG_CFG_MIGRATE_WARN = (
        "[설정] 구성 파일 버전이 앱 보다 높습니다 (파일: v{}, 앱: v{}). 일부 설정이 유실될 수 있습니다."
    )
    LOG_CFG_DELETE_FAIL_MSG = "[설정] 설정 파일 삭제 실패: {}"
    LOG_CFG_LOG_CLEANUP_DONE_MSG = "[설정] 로그 파일 {}개 삭제 완료"
    LOG_CFG_INVALID_VER = "[설정] 구성 파일 버전이 올바르지 않습니다. 기본값을 사용합니다."
    LOG_CFG_MIGRATION = "[설정] 구성 마이그레이션: v{} -> v{}"
    LOG_CFG_APPDATA_FALLBACK = "[설정] AppData 폴더 접근 실패({}). 임시 폴더로 전환합니다: {}"
    LOG_CFG_SESSION_DIR_CLEAR_FAIL = "[설정] 세션 폴더 삭제 실패: {}"
    LOG_CFG_ALL_DATA_CLEARED = "[설정] 모든 데이터 초기화 완료"
    LOG_SES_SAVE_FAIL = "[세션] 저장 실패 ({}): {}"
    LOG_SES_LOAD_FAIL = "[세션] 로드 실패 ({}): {}"
    LOG_SES_DELETE_FAIL = "[세션] 삭제 실패 ({}): {}"
    LOG_SES_LIST_FAIL = "[세션] 목록 조회 실패: {}"
    LOG_CFG_SESSION_TITLE_READ_FAIL = "[세션] 세션 제목 읽기 실패: {}"
    LOG_CFG_SESSION_SEARCH_FAIL = "[세션] 세션 탐색 중 오류 발생: {}"
    LOG_SYS_STDERR_FLUSH_FAIL = "[시스템] 표준 에러 플러시 실패: {}"
    LOG_SYS_STARTUP_LOG_CLEANUP_FAIL = "[시스템] 시작 시 로그 정리 실패: {}"
    LOG_SYS_CLOSE_CLEANUP_FAIL = "[시스템] 종료 시 정리 작업 실패: {}"
    LOG_SYS_HANDLER_CLEANUP_FAIL = "[시스템] 클린업 핸들러 오류: {}"
    LOG_SYS_CRITICAL_POPUP_FAIL = "[시스템] 치명적 오류 팝업 표시 실패: {}"
    LOG_SYS_LOG_CLEANUP_FAILURE = "[시스템] 로그 정리 실패: {}"
    LOG_CFG_UNEXPECTED_LOAD_ERROR = "[설정] 예기치 않은 구성 로드 오류: {}"
    LOG_CFG_BACKUP_CLEANUP_FAIL = "[설정] 백업 파일 정리 실패: {}"
    LOG_CFG_TEMP_REMOVE_FAIL = "[설정] 임시 파일 제거 실패: {}"
    LOG_SES_TEMP_CLEANUP_FAIL = "[세션] 임시 파일 정리 실패: {}"
    LOG_CFG_LOG_FILE_CLEANUP_FAIL = "[설정] 로그 파일 정리 실패 ({}): {}"
    # =========================================================================
    # [10] 검색 및 스캔 로그 (Search & Scan Logs) - 형식: [검색 / 스캔 / 엔진] 메시지
    # =========================================================================
    LOG_SCH_STARTED = "=== [검색] 시작 (초기화 및 설정 확인) ==="
    LOG_SCH_ERROR_START = "[검색] 시작 중 문제 발생: {}"
    LOG_SCH_COND_QUERY = "   └─ 검색어: '{}'"
    LOG_SCH_COND_FOLDER = "   └─ 폴더 목록: '{}'"
    LOG_SCH_COND_FILENAME = "   └─ 파일명 필터: {}"
    LOG_SCH_COND_EXT = "   └─ 확장자 목록: '{}' (특수 검색: {})"
    LOG_SCH_PATH_ENTER = "=== [검색] 엔진 구동 ==="
    LOG_SCH_SCAN_DONE = "[스캔] 1/2단계 완료: {}개 대상 파일 확보 ({:.3f}초)"
    LOG_SCH_SCAN_DONE_WITH_SKIPPED = "[스캔] 1/2단계 완료: {}개 대상 파일 확보 (건너뜀: {}개, 소요 시간: {:.3f}초)"
    LOG_SCH_SCAN_DONE_SIMPLE = "[스캔] 1/2단계 완료 ({:.3f}초)"
    LOG_SCH_SCAN_STARTED_TYPE = "[스캔] 1/2단계{} 스캔 시작..."
    LOG_SCH_SCAN_TYPE_RUST = "Rust (기본)"
    LOG_SCH_SCAN_TYPE_PYTHON = "Python (정밀/복합)"
    LOG_SCH_SKIPPED_FILES_LIST = "[스캔] 건너뛴 파일 목록:"
    LOG_SCH_SCAN_DONE_FAST_PATH = "[스캔] 1/2단계 완료 (빠른 경로)"
    LOG_SCH_SEARCH_DONE = "=== [검색] 종료 (전체 소요 시간: {:.3f}초) ==="
    LOG_SCH_NO_FILES = "[검색] 검색할 파일이 없습니다."
    LOG_SCH_EMPTY_QUERY = "[검색] 검색어가 비어 있습니다."
    LOG_SCH_FOLDER_ACCESS_DENIED = "[스캔] 폴더 접근 거부: {} ({})"
    LOG_SCH_SCAN_OS_ERROR = "[스캔] 폴더 스캔 중 OS 오류 발생: {} ({})"
    LOG_SCH_RUST_MODE = "[엔진] Rust 가속 모드 활성화"
    LOG_SCH_PYTHON_MODE = "[엔진] Python 호환 모드 활성화"
    LOG_SCH_HYBRID_MODE = "[엔진] 하이브리드 모드 (Rust 스캔 + Python 검색)"
    LOG_SCH_STOP_REQUESTED = "[제어] 중지 요청됨..."
    LOG_SCH_STOPPED_BY_USER = "[제어] 사용자에 의해 중지됨."
    LOG_SCH_RESTART_PENDING = "[제어] 재시작 대기 중..."
    LOG_SCH_RESTART_SCHEDULED = "[제어] 재시작 예약됨..."
    LOG_SCH_SKIP_COUNT = "[건너뜀] {}개 파일 제외됨."
    LOG_SCH_SKIP_REASON = "   └─ {} (사유: {})"
    LOG_SCH_SKIP_SIMPLE = "   └─ {}"
    LOG_SCH_RETRY_PYTHON = "[전환] Python 엔진으로 재시도 ({})"
    LOG_SCH_ALL_FILES_GUIDE = "[안내] 전체 파일 모드"
    LOG_SCH_FILENAME_FILTER_GUIDE = "[안내] 파일명 필터 적용: {}"
    LOG_SCH_SMART_SCAN_STARTED = "[스캔] 1/2단계 파일 스캔 시작 (Smart Scan: '{}')"
    LOG_SCH_SMART_SCAN_SKIPPED = "[스캔] 스마트 스캔 건너뜀: {} (사유: {})"
    LOG_SCH_LOG_CLEANUP_DONE = "[시스템] 로그 파일 {}개 정리 완료"
    LOG_SCH_ALL_DONE = "=== [검색] 모든 작업이 종료되었습니다. (전체: {:.3f}초) ==="
    LOG_WKR_INIT = "[워커] 2/2단계 워커 프로세스 초기화..."
    LOG_WKR_STARTED = "[엔진] 병렬 데이터 처리 시작 ('{}' | 필터: {} | {})"
    LOG_WKR_RUNNING = "   └─ 처리 중: {}개 파일..."
    LOG_WKR_PROGRESS = "   └─ 진행률 {}% ({}/{})"
    LOG_WKR_COMPLEX_ACT = "[엔진] 유니코드 정밀 모드(Python) 사용"
    LOG_WKR_PYTHON_ACT = "[엔진] Python 엔진 검색 진행"
    LOG_WKR_RUST_ACT = "[엔진] Rust 통합 엔진 활성화 ({}개 경로 대상)"
    LOG_WKR_DONE = "[엔진] 병렬 검색 종료 (발견: {}, 매치: {}) - 소요 시간: {:.3f}초"
    LOG_WKR_EXCEL_SCAN = "[워커] 엑셀 파일 검색 활성화"
    LOG_WKR_STOP_EVENT_FALLBACK = "[워커] threading.Event를 중지 이벤트로 사용합니다."
    LOG_WKR_STOPPED = "[워커] 중지됨."
    LOG_WKR_STOP_SIGNAL = "[워커] 중지 신호."
    LOG_WKR_ADAPTIVE_POLICY_INFO = "[워커] 적응형 정책 적용: 코어 {}개 중 {}개 워커 사용"
    # =========================================================================
    # [11] 리소스 및 성능 로그 (Resource & Performance) - 형식: [리소스 / 성능] 메시지
    # =========================================================================
    LOG_RES_DATA_DIR_FAIL = "[리소스] 데이터 폴더 열기 실패: {}"
    LOG_RES_LOG_CLEANUP_FAIL = "[리소스] 로그 정리 실패: {}"
    LOG_RES_CLEANUP_START = "[리소스] 정리 시작..."
    LOG_RES_CLEANUP_ERROR = "[리소스] 정리 오류: {}"
    LOG_RES_NOT_FOUND = "[리소스] 파일을 찾을 수 없음: {}"
    LOG_PERF_MANAGER_INIT = "[성능] 전역 멀티프로세싱 매니저 생성 완료"
    LOG_PERF_MANAGER_FAIL = "[성능] 매니저 생성 실패: {}"
    LOG_PERF_MANAGER_SHUTDOWN = "[성능] 전역 멀티프로세싱 매니저 종료 완료"
    LOG_EXECUTOR_SHUTDOWN_ERROR = "[성능] 실행기(Executor) 종료 오류: {}"
    LOG_CLEANUP_CHILDREN = "[성능] {}개의 자식 프로세스 정리 중..."
    LOG_ZOMBIE_CLEANUP_ERROR = "[성능] 좀비 프로세스 정리 중 오류: {}"
    LOG_EXECUTOR_STOPPING = "[성능] 실행기(Executor) 중지 중..."
    LOG_EXECUTOR_FORCE_STOP = "[성능] 실행기 강제 종료 중..."
    LOG_WKR_HANG_DETECTED = "[성능] 워커 지연 감지 (경과: {:.2f}초). 복구 중..."
    LOG_WKR_HANG_RECOVERY = "[성능] 작업 지연으로 실행기 재생성"
    LOG_THREAD_FORCE_TERM = "[스레드] 강제 종료됨."
    LOG_PERF_SKIP_RESIZE = "[성능] 대량 데이터({}행)로 인한 자동 폭 조절 건너뜀"
    LOG_PERF_SKIP_MATCH_RESIZE = "[성능] 대량 매치 데이터({}행)로 인한 상세 뷰 자동 폭 조절 건너뜀"
    LOG_PERF_ADJUST_MATCH_FAIL = "[성능] 상세 컬럼 폭 조정 실패: {}"
    LOG_PERF_MANAGER_SHUTDOWN_ERROR = "[성능] 전역 멀티프로세싱 매니저 종료 오류: {}"
    LOG_PERF_FUTURE_CANCEL_ERROR = "[성능] 작업 취소(Future) 오류: {}"
    LOG_PERF_EVENT_UPGRADE = "[성능] 멀티프로세스 검색을 위해 Manager.Event로 stop_event가 업그레이드되었습니다."
    LOG_WKR_MANAGER_SHUTDOWN_IGNORED = "[워커] 전역 매니저 종료 무시됨 (채널 닫힘): {}"
    LOG_WKR_SIGNAL_EMIT_FAIL = "[워커] 시그널 전송 실패 ({}): {}"
    LOG_WKR_FUTURE_SCHEDULING_SKIPPED = "[워커] Future 스케줄링 건너뜀: {}"
    LOG_WKR_FUTURE_SUBMISSION_FAIL = "[워커] Future 제출 실패: {}"
    LOG_WKR_HANG_TIMEOUT = "[워커] 배치 검색이 중단 시간({}s)에 도달하여 강제 종료합니다."
    LOG_WKR_BATCH_FAILED = "[워커] 배치 작업 실패: {}"
    LOG_WKR_EXECUTOR_SHUTDOWN_ERROR = "[워커] 실행기 종료 오류: {}"
    LOG_SYS_RUST_PATH = "[SSOT] 로드된 Rust 엔진 경로: {}"
    LOG_SYS_RUST_HASH = "[SSOT] Rust 엔진 SHA-256: {}"
    LOG_SCH_RUST_PERF_STATS = "[Rust] 원시 카운트: {}, 호출: {:.4f}s, 정규화: {:.4f}s"
    LOG_SCH_ENGINE_ISOLATION_BAIL = "[엔진 게이트] 고립 정책에 의한 중단 (사유: {}): {}"
    LOG_SCH_RUST_SMART_SCAN_FATAL = "[치명적] 스마트 스캔 중 근본 예외 발생: {}"
    LOG_SCH_BINARY_COUNT_PARSE_FAIL = "[엔진] 바이너리 카운트 파싱 실패 (길이 {}): {}"
    LOG_SCH_EXISTENCE_DECODE_FAIL = "[_fast_existence_check] 디코딩/폴백 중단: {}"
    LOG_SCH_EXISTENCE_JSON_FALLBACK = "[_fast_existence_check] {}: 디코딩/JSON 실패 (심층 검색 폴백): {}"
    LOG_SCH_EXISTENCE_UNEXPECTED = "[_fast_existence_check] {} 예기치 않은 오류: {}"
    LOG_SYS_RUST_NO_FALLBACK = "[시스템] Rust 엔진을 로드할 수 없습니다. (Python 폴백 정책 제한됨)"
    # =========================================================================
    # [12] 에러 메시지 (Error Messages) - 형식: [오류] 메시지
    # =========================================================================
    ERROR_TITLE = "오류"
    ERROR_UNKNOWN = "알 수 없는 오류"
    ERROR_IO_GENERIC = "[오류] IO 오류: {}"
    ERROR_UNEXPECTED_FILE = "[오류] 파일 '{}' 처리 중 예기치 못한 문제: {}"
    ERROR_JSON_PARSE = "[오류] JSON 파싱 실패: {}"
    ERROR_EXPORT_FAIL = "[오류] 내보내기 실패: {}"
    ERROR_OPEN_DIR_FAILED = "[오류] 디렉토리 열기 실패: {}"
    ERROR_IO_DURING_SEARCH = "[오류] 검색 중 IO 오류: {}"
    ERROR_STOP_SEARCH_TAB = "[오류] 중지 처리 실패: {}"
    ERROR_EXCEL_ACCESS = "[오류] Excel 접근 실패: {}"
    ERROR_EXCEL_SIGNATURE = "[오류] 유효하지 않은 Excel 서명"
    ERROR_EXCEL_PROCESS = "[오류] Excel 처리 실패: {}"
    ERROR_EXCEL_CALAMINE = "[오류] Excel 검색을 위해 python-calamine 라이브러리가 필요합니다."
    ERROR_EXCEL_CALAMINE_REQ = "[오류] Excel 검색을 위해 python-calamine 라이브러리가 필요합니다."
    ERROR_EXCEL_LIB = "[오류] Excel 라이브러리 문제: {}"
    ERROR_SEARCH_EXCEL = "[오류] Excel 검색 실패 {}: {}"
    ERROR_SEARCH_EXCEL_SHEET = "[오류] 시트 '{}' 검색 실패: {}"
    ERROR_EXCEL_PANIC = "[오류] 치명적인 Excel 오류 (Panic): {}"
    ERROR_JSON_RECURSION = "[오류] JSON 재귀 오류"
    ERROR_JSON_DEPTH_LIMIT = "[오류] JSON 깊이 제한 초과"
    ERROR_XML_PARSE = "[오류] XML 파싱 실패: {}"
    ERROR_FILE_ACCESS_BINARY = "[오류] 파일 접근 실패 (바이너리 체크): {}"
    ERROR_READ_FILE = "[오류] 파일 읽기 실패 {}: {}"
    ERROR_SEARCH_CRITICAL_TITLE = "검색 오류"
    ERROR_SEARCH_CRITICAL_MSG = "검색 중 치명적인 오류가 발생했습니다.\n로그를 확인해주세요.\n\n오류: {}"
    ERROR_SEARCH_START_FAIL = "[오류] 시작 실패:\n{}\n\n{}"
    ERROR_PROCESS_CRITICAL = "[오류] 치명적인 처리 문제: {}"
    ERROR_SEARCH_UNKNOWN = "[오류] 알 수 없는 검색 오류: {}"
    ERROR_SESSION_SAVE = "[오류] 세션 저장 실패: {}"
    ERROR_LIMIT_REACHED = "[중단] 결과가 너무 많아 안정성을 위해 검색을 중지했습니다. (최대 {}건)"
    ERROR_MEMORY_CRITICAL = "[중단] 시스템 메모리가 부족하여 안정성을 위해 검색을 중지했습니다."
    TITLE_LIMIT_REACHED = "검색 제한 도달"
    MSG_RESULT_LIMIT_REACHED = "검색 결과가 너무 많아(100,000건 초과) 안정성을 위해 검색을 즉시 중지합니다.\n발견된 항목까지만 리스트에 표시됩니다."
    MSG_MATCH_LIMIT_PER_FILE = "(파일당 최대 매치 수 {}건 도달)"
    ERROR_WKR_HANG_RECOVERY = "[오류] 작업 지연으로 실행기 재생성"
    ERROR_NO_EXTENSION = "[오류] 최소 하나의 확장자를 선택해주세요."
    ERR_CRITICAL_SYSTEM = "[시스템] 치명적인 시스템 오류: {}"
    ERR_BATCH_SEARCH_FAIL = "[워커] 배치 검색 실패: {}"
    LOG_SCH_BINARY_CHECK_FAIL = "[오류] 바이너리 확인 실패 ({}): {}"
    LOG_SCH_PARSE_ERROR = "[오류] 파싱 실패 {} ({}): {}"
    LOG_SCH_UNEXPECTED_ERROR = "[오류] 예기치 못한 문제 {} ({}): {}"
    LOG_SCH_ERROR = "[오류] : {}"
    LOG_SCH_RUST_ENGINE_ERROR = "[오류] Rust 엔진 오류 ({}): {}"
    LOG_SCH_RUST_JSON_FAIL = "[오류] Rust JSON 검색 실패 ({}): {}"
    LOG_SCH_RUST_DIR_SEARCH_ERROR = "[오류] 디렉토리 검색 오류 ({}): {}"
    LOG_SCH_RUST_DIR_FATAL = "[오류] Rust 디렉터리 검색 치명적 오류 ({}): {}"
    LOG_SCH_RUST_DIR_BASE_FATAL = "[오류] Rust 디렉터리 검색 치명적 BaseException ({}): {}"
    LOG_SCH_RUST_FILELIST_FATAL = "[오류] Rust 파일 목록 검색 치명적 오류 ({}): {}"
    LOG_SCH_RUST_SMART_SCAN_ERROR = "[오류] 스마트 스캔 오류 ({}): {}"
    LOG_SRCH_RUST_MEM_GUARD_WARN = "[검색] Rust 엔진 메모리 가드 작동: {}"
    LOG_SCH_ERROR_FILE = "[오류] 파일 처리 실패 ({}): {}"
    LOG_SCH_RUST_EXCEL_FAIL = "[오류] Rust Excel 검색 실패 ({}): {}"
    LOG_SCH_JSON_FAIL = "[오류] JSON 검색 실패: {}"
    LOG_SCH_XML_FAIL = "[오류] XML 검색 실패: {}"
    LOG_SCH_RUST_XML_FAIL = "[오류] Rust XML 검색 실패 ({}): {}"
    LOG_SCH_RUST_ARCHIVE_FAIL = "[오류] Rust Archive 검색 실패 ({}): {}"
    LOG_SCH_ARCHIVE_FAIL = "[오류] Archive 검색 실패: {}"
    LOG_SCH_JSON_LIMIT = "[오류] JSON 깊이 제한 도달"
    LOG_SCH_BINARY_CHECK_ERROR = "[오류] 바이너리 점검 문제: {}"
    LOG_SCH_JSON_RECURSION = "[오류] JSON 재귀 호출 감지"
    LOG_SCH_ENCODING_ERROR = "[오류] 인코딩 감지 실패 ({}): {}"
    LOG_SCH_STREAM_ERROR = "[오류] 스트림 처리 실패: {}"
    LOG_SCH_STOP_THREAD_ERR = "[오류] 스레드 중지 실패: {}"
    LOG_SCH_SCAN_THREAD_ERROR = "[오류] 스캔 스레드 종료 중 오류 발생: {}"
    LOG_SCH_SEARCH_THREAD_ERROR = "[오류] 검색 스레드 종료 중 오류 발생: {}"
    LOG_SCH_EXCEL_SHEET_ERROR_DETAIL = "[검색] 엑셀 시트 파싱 오류: {}"
    LOG_SCH_EXCEL_ENGINE_PANIC_EXT = "[검색] 엑셀 엔진 패닉 [{}]: {}"
    LOG_SCH_EXCEL_ENGINE_PANIC = "[검색] 엑셀 엔진 패닉: {}"
    LOG_THEME_APPLY_FAIL = "[화면] 테마 적용 실패 (테마={}): {}"
    ERROR_SORT_WORKER = "[오류] 정렬 워커(SortWorker) 오류: {}"
    ERROR_GLOBAL_SORT_WORKER = "[오류] 전역 정렬 워커(GlobalSortWorker) 오류: {}"
    LOG_WKR_BATCH_ERROR = "[워커] 배치 오류: {}"
    LOG_WKR_BATCH_RETRY = "[워커] 재시도: {}"
    LOG_WKR_BATCH_FAILED_DETAIL = "[워커] 배치 처리 실패 ({}개 파일). 샘플: {}"
    LOG_WKR_BATCH_ERROR_DETAIL = "[워커] 배치 오류 ({}개 항목): {}"
    LOG_WORKER_ERROR_SIGNAL_FAIL = "[워커] 오류 신호 전송 실패"
    LOG_WORKER_FINISH_SIGNAL_FAIL = "[워커] 완료 신호 전송 실패"
    LOG_QT_INFO = "[Qt] 정보: {}"
    LOG_QT_WARNING = "[Qt] 경고: {}"
    LOG_QT_CRITICAL = "[Qt] 치명적 오류: {}"
    LOG_QT_FATAL = "[Qt] 치명적 오류: {}"
    LOG_SCH_ERROR_START_PREFIX = "[검색] 시작 중 문제 발생: {}"
    LOG_SCH_SCAN_OS_ERROR_PREFIX = "[스캔] 폴더 스캔 중 OS 오류: {}"
    # =========================================================================
    # [13] 경로 스킵 사유 (Skip Reasons) - Prefix 포함
    # =========================================================================
    SKIP_REASON_WALK = "[오류] 경로 순회 실패: {}"
    SKIP_REASON_OPEN = "[오류] 파일 열기 실패: {}"
    SKIP_REASON_METADATA = "[오류] 메타데이터 읽기 실패: {}"
    SKIP_REASON_MMAP = "[오류] 메모리 맵핑 실패: {}"
    SKIP_REASON_TOO_LARGE = "[오류] 파일 용량 초과: {}"
    SKIP_REASON_MEMORY_GUARD = "[오류] 메모리 보호 작동: {}"
    SKIP_REASON_PANIC = "[오류] 엔진 패닉 발생: {}"
    SKIP_REASON_CRITICAL = "[오류] 치명적 오류: {}"
    SKIP_REASON_UNKNOWN = "[오류] 알 수 없는 무시 사유: {}"
