from sf_utils.version_helper import get_app_version


class AppStrings:
    """
    애플리케이션에서 사용하는 모든 사용자 인터페이스 문자열 및 로그/에러 메시지를 관리하는 클래스입니다.
    가독성과 유지보수성을 위해 카테고리별로 그룹화되어 있습니다.
    """

    # =========================================================================
    # [1] 기본 앱 정보 (Basic App Info)
    # =========================================================================
    APP_TITLE = "StringFinder"
    APP_VERSION = get_app_version()  # pyproject.toml 기반 Single Source
    APP_AUTHOR = "Antigravity"
    TITLE_CRITICAL_ERROR = "StringFinder 오류"
    TITLE_QT_WARNING = "스레드 경고"
    STATUS_ELAPSED_TIME = "소요 시간: {:02d}:{:02d}"
    MSG_SEARCH_SINGLE_CHAR_WARN = "검색어가 너무 짧아 검색 시간이 오래 걸릴 수 있습니다. 진행하시겠습니까?"
    MSG_ALREADY_RUNNING = "프로그램이 이미 실행 중입니다."
    # =========================================================================
    # [2] UI 요소 (Buttons, Menus, Labels)
    # =========================================================================
    SEARCH_LABEL = "문자열 검색"
    ADD_TAB_BTN = "+"
    ADD_FOLDER_BTN = "폴더 추가"
    ADD_EXT_BTN = "추가"
    SELECT_ALL_BTN = "전체 선택"
    DESELECT_ALL_BTN = "전체 해제"
    BTN_CLOSE = "닫기"
    SEARCH_BTN = "검색"
    SEARCH_BTN_STOP = "중지"
    SEARCH_BTN_STOPPING = "중지 중..."
    OPEN_FILE = "파일 열기"
    OPEN_FOLDER = "폴더 열기"
    OPEN_LINE_IN_EDITOR = "해당 줄 열기"
    COPY_PATH = "경로 복사 (Ctrl+C)"
    COPY_CONTENT = "내용 복사 (Ctrl+C)"
    LOG_FILTER_LABEL = "로그 필터:"
    LOG_CLEAR_BTN = "로그 지우기"
    FILENAME_FILTER_LABEL = "파일명 필터:"
    SELECT_FOLDER_TITLE = "폴더 선택"
    PAGINATION_PREV = "이전"
    PAGINATION_NEXT = "다음"
    PAGINATION_PAGE = "페이지:"
    PAGINATION_OF = "/"
    PAGINATION_DISPLAY = "표시:"
    PAGINATION_SIZE_1000 = "1000"
    PAGINATION_SIZE_2000 = "2000"
    PAGINATION_SIZE_5000 = "5000"
    SUCCESS_TITLE = "성공"
    INFO_TITLE = "알림"
    INFO_CLEAR_SUCCESS = "데이터가 성공적으로 삭제되었습니다."
    INFO_RESET_LAYOUT_DONE = "레이아웃이 초기화되었습니다."
    INFO_LOGS_DELETED = "로그가 삭제되었습니다."
    HISTORY_CLEAR_ALL = "--- 기록 삭제 ---"
    DOCK_SEARCH_TITLE = "검색 설정"
    DOCK_FOLDER_TITLE = "폴더 목록(하위 폴더 포함)"
    DOCK_EXT_TITLE = "확장자 목록"
    DOCK_FILENAME_TITLE = "파일명 필터"
    DOCK_RESULT_TITLE = "검색 결과"
    MENU_LOCK_LAYOUT = "레이아웃 잠금"
    MENU_RESET_LAYOUT = "레이아웃 초기화"
    TAB_RENAME_TITLE = "탭 이름 변경"
    TAB_RENAME_PROMPT = "새 탭 이름을 입력하세요:"
    TAB_CLOSE_MENU = "탭 닫기"
    SEARCH_TAB_DEFAULT_TITLE = "검색"
    SEARCH_TAB_TITLE_TEMPLATE = "{} {}"
    TAB_RESULTS = "검색 결과"
    TAB_LOGS = "로그"
    SETTINGS_TITLE = "설정"
    SETTINGS_GROUP_GENERAL = "일반"
    SETTINGS_GROUP_APPEARANCE = "화면"
    SETTINGS_GROUP_LOG = "로그"
    SETTINGS_GROUP_DATA = "데이터"
    SETTINGS_GROUP_ADVANCED = "고급"
    EXTERNAL_EDITOR_GROUP = "줄 열기 프로그램"
    EXTERNAL_EDITOR_LABEL = "프로그램:"
    EXTERNAL_EDITOR_SYSTEM = "시스템 기본 앱"
    EXTERNAL_EDITOR_VSCODE = "Visual Studio Code"
    EXTERNAL_EDITOR_CURSOR = "Cursor"
    EXTERNAL_EDITOR_NOTEPADPP = "Notepad++"
    EXTERNAL_EDITOR_SUBLIME = "Sublime Text"
    EXTERNAL_EDITOR_CUSTOM = "사용자 지정"
    EXTERNAL_EDITOR_PATH_LABEL = "실행 파일:"
    EXTERNAL_EDITOR_BROWSE = "찾아보기"
    EXTERNAL_EDITOR_FILE_FILTER = "실행 파일 (*.exe);;모든 파일 (*)"
    
    ADVANCED_MAX_TOTAL_MATCHES = "전체 최대 매치 수"
    ADVANCED_MAX_PER_FILE_MATCHES = "파일당 최대 매치 수"
    ADVANCED_MAX_JSON_DOM_SIZE = "JSON 최대 파싱 메모리 한계"
    ADVANCED_MAX_SMALL_FILE_SIZE = "소형 파일 직접 읽기 임계치"
    ADVANCED_JSON_MMAP_THRESHOLD = "JSON 스트리밍 Mmap 전환 기준"
    ADVANCED_TIMEOUT_WORKER_HANG = "워커 무응답 강제 종료 타임아웃"
    ADVANCED_MAX_CHECK_CELLS = "존재 여부 시 최대 검사 셀 (엑셀)"
    ADVANCED_MAX_JSON_DEPTH = "JSON 노드 파싱 최대 깊이 제한"

    TOOLTIP_MAX_TOTAL_MATCHES = "프로그램 전체에서 한 번의 검색에 표시할 수 있는 총 매치 허용 개수입니다."
    TOOLTIP_MAX_PER_FILE_MATCHES = "하나의 파일 내에서 허용되는 최대 결과 수입니다. 초과 시 경고와 함께 스킵합니다."
    TOOLTIP_MAX_JSON_DOM_SIZE = "JSON 파일 크기가 이 값을 넘으면 시스템 OOM 방지를 위해 정밀 파싱을 생략합니다."
    TOOLTIP_MAX_SMALL_FILE_SIZE = "이 크기 미만의 작은 파일은 Mmap 대신 일반 파일 읽기로 통째로 올려 검색 속도를 높입니다."
    TOOLTIP_JSON_MMAP_THRESHOLD = "이 크기를 넘는 JSON 파일은 RAM을 절약하기 위해 Mmap 기반의 스트리밍 파서로 처리됩니다."
    TOOLTIP_TIMEOUT_WORKER_HANG = "단일 파일 검색 프로세스가 이 시간 동안 무응답일 경우 데드락으로 간주하고 죽입니다."
    TOOLTIP_MAX_CHECK_CELLS = "결과를 담지 않는 '존재 여부 확인' 모드에서 무한 지연을 막기 위한 빈 셀 검사 한계점입니다."
    TOOLTIP_MAX_JSON_DEPTH = "비정상적으로 깊은 JSON 트리를 만났을 때 스택 오버플로우를 막기 위한 계층 뎁스(Depth) 제한입니다."

    UNIT_COUNT = "건"
    UNIT_MB = "MB"
    UNIT_SEC = "초"
    UNIT_CELL = "셀"
    UNIT_DEPTH = "단위(층)"

    BTN_RESET_ADVANCED = "고급 설정 초기값으로 복원"
    THEME_LABEL = "테마:"
    THEME_DARK = "다크"
    THEME_LIGHT = "라이트"
    LOG_RETENTION_LABEL = "로그 보관:"
    BTN_DELETE_ALL_LOGS = "모든 로그 삭제"
    MSG_DELETE_LOGS_CONFIRM = "모든 로그 파일을 삭제하시겠습니까?"
    MAX_FILES_LABEL = "최대 파일 수:"
    MAX_DAYS_LABEL = "최대 보관 일수:"
    OPEN_DATA_DIR_BTN = "데이터 폴더 열기"
    CLEAR_ALL_DATA_BTN = "모든 데이터 삭제"
    CLEAR_ALL_DATA_CONFIRM = "모든 설정과 기록을 삭제하시겠습니까?"
    COMBO_ENABLE = "사용"
    COMBO_DISABLE = "사용 안 함"
    COMBO_LOCKED = "잠금"
    COMBO_UNLOCKED = "해제"
    # =========================================================================
    # [3] 도움말 및 툴팁 (Tooltips & Guidance)
    # =========================================================================
    COMPLEX_SEARCH_LABEL = " (느림)"
    COMPLEX_SEARCH_TOOLTIP = (
        "영어, 한글, 일반 특수 문자가 아닌 경우까지 검색 합니다.\n"
        "예: 독일어(ß↔ss), 프랑스어(Œ↔oe), 원문자(㉮↔가) 및 복잡한 유니코드 변형\n"
        "정밀 하게 검사하는 대신, 속도가 느립니다."
    )
    EXCLUDE_HIDDEN_LABEL = "시스템 항목 제외"
    EXCLUDE_HIDDEN_TOOLTIP = (
        "윈도우의 '숨김' 속성이 설정된 폴더와 파일을 검색에서 제외합니다.\n"
        ".git, node_modules, AppData 등 불필요한 스캔을 줄여 속도가 대폭 향상됩니다."
    )
    EXCLUDE_BINARY_LABEL = "바이너리 파일 제외"
    EXCLUDE_BINARY_TOOLTIP = (
        "이미지, 실행 파일(exe, dll) 등 바이너리 파일을 검색 대상에서 제외합니다.\n"
        "항상 검색이 필요한 특수 모드(Excel 등)나 직접 지정한 확장자는 제외 대상에서 보호됩니다."
    )
    BOOLEAN_SEARCH_LABEL = "존재 여부만 확인 (고속)"
    BOOLEAN_SEARCH_TOOLTIP = (
        "파일 내에 해당 텍스트가 존재하는지만 빠르게 확인합니다.\n"
        "첫 번째 일치 항목을 찾으면 즉시 다음 파일로 넘어가므로 매우 빠릅니다.\n"
        "상세 매치(줄 번호 등)는 제공되지 않습니다."
    )
    SPECIAL_SEARCH_LABEL = "특수 검색:"
    SPECIAL_SEARCH_OFF = "끄기"
    SPECIAL_SEARCH_ITEMS = [
        "끄기",
        "XML (부분 일치)",
        "XML (정확히 일치)",
        "JSON (부분 일치)",
        "JSON (정확히 일치)",
        "Excel (부분 일치)",
        "Excel (정확히 일치)",
    ]
    SPECIAL_SEARCH_XML = "XML (부분 일치)"
    SPECIAL_SEARCH_JSON = "JSON (부분 일치)"
    SPECIAL_SEARCH_EXCEL = "Excel (부분 일치)"
    # =========================================================================
    # [4] 입력 필드 및 플레이스홀더 (Placeholders)
    # =========================================================================
    SEARCH_EDIT_PLACEHOLDER = (
        "검색할 문자열 입력...(검색을 원하는 문자열이 '한글', '영어', '일반 특수 문자'가 아닌 경우. 정밀 검색 사용)"
    )
    EXT_EDIT_PLACEHOLDER = "확장자 (예: txt)"
    FILENAME_EDIT_PLACEHOLDER = "파일명 필터 (예: npc, fo / 콤마 구분)..."
    FILENAME_LIST_PLACEHOLDER = "필터 단어 (예: npc)"
    RESULT_FILTER_FILE_PLACEHOLDER = "파일 필터..."
    RESULT_FILTER_FOLDER_PLACEHOLDER = "폴더 필터..."
    MATCH_FILTER_LIST_PLACEHOLDER = "목록 필터..."
    MATCH_FILTER_LINE_PLACEHOLDER = "라인 필터..."
    MATCH_FILTER_CONTENT_PLACEHOLDER = "내용 필터..."
    MATCH_FILTER_NAME_PLACEHOLDER = "이름 필터..."
    MATCH_FILTER_KEY_PLACEHOLDER = "키 필터..."
    MATCH_FILTER_VALUE_PLACEHOLDER = "값 필터..."
    MATCH_FILTER_EXCEL_SHEET_PLACEHOLDER = "시트 필터..."
    MATCH_FILTER_EXCEL_CELL_PLACEHOLDER = "셀 필터..."
    MATCH_FILTER_EXCEL_VAL_PLACEHOLDER = "값 필터..."
    # =========================================================================
    # [5] 테이블 헤더 (Table Headers)
    # =========================================================================
    HEADER_COUNT = "개수"
    HEADER_FOLDER = "폴더"
    HEADER_FILE = "파일"
    HEADER_POSITION = "위치"
    HEADER_CONTENT = "내용"
    HEADER_JSON_KEY = "키"
    HEADER_JSON_VALUE = "값"
    HEADER_XML_NAME = "키"  # 이름에서 키로 변경
    HEADER_XML_VALUE = "값"
    HEADER_EXCEL_SHEET = "시트"
    HEADER_EXCEL_CELL = "셀"
    HEADER_EXCEL_VALUE = "값"
    HEADER_LIST = "목록"
    # =========================================================================
    # [6] 상태 및 결과 메시지 (Status & Results)
    # =========================================================================
    STATUS_READY = "준비"
    STATUS_IDLE = "대기 중"
    STATUS_SCANNING = "파일 스캔 중..."
    STATUS_SEARCHING = "문자열 검색 중..."
    STATUS_STOPPING = "중지 중..."
    STATUS_FOUND_COUNT = "{}개 파일에서 검색 완료"
    STATUS_ERROR_PREFIX = "[오류] "
    RESULT_SUMMARY_TEMPLATE = "발견: {}개 파일 | 매치: {}개"
    RESULT_EMPTY_MSG = "검색을 시작 해주세요."
    RESULT_SEARCHING_MSG = '"{}" 검색 중 입니다.'
    RESULT_EMPTY_NO_FOLDER = "검색할 폴더를 추가해주세요."
    RESULT_EMPTY_NO_MATCH = "'{}'에 대한 검색 결과가 없습니다. 누락된 문자열이 있을 경우 정밀 검색을 사용해주세요."
    RESULT_SUMMARY_FORMAT = "문자열 포함 파일 수 : {file_count} | 전체 매칭된 문자열의 수 : {match_count} | 건너뛴 파일 수 : {skip_count} | 시간 : {duration}s"
    SELECTED_FILE_INFO_TEMPLATE = "📄 {}  (총 {}건 매치)"
    CONTEXT_PREVIEW_TITLE = "문맥 미리보기"
    CONTEXT_PREVIEW_BEFORE_LABEL = "위 문맥:"
    CONTEXT_PREVIEW_AFTER_LABEL = "아래 문맥:"
    CONTEXT_PREVIEW_LINE_UNIT = "줄"
    CONTEXT_PREVIEW_PLACEHOLDER = "매치 항목을 선택하면 전후 문맥이 표시됩니다."
    CONTEXT_PREVIEW_FILE_UNAVAILABLE = "[파일이 존재하지 않거나 접근할 수 없습니다]"
    CONTEXT_PREVIEW_SPECIAL_MATCH = "[특수 데이터 매치]\n\n위치: {}\n내용: {}"
    CONTEXT_PREVIEW_READ_FAILED = "[문맥 미리보기 읽기 실패]\n{}"
    CONTEXT_PREVIEW_SCAN_LIMIT = "[문맥 미리보기 생략]\n대상 줄이 너무 멀어 UI 보호를 위해 읽기를 중단했습니다."
    CONTEXT_PREVIEW_TRUNCATED = "\n[문맥이 길어 일부만 표시됩니다]"
    SUMMARY_PREFIX_SEARCHING = "[검색 중] "
    SUMMARY_PREFIX_STOPPED = "[검색 중지] "
    SUMMARY_PREFIX_FINISHED = "[검색 완료] "
    RESULT_MSG_SKIPPED_DETAILS = "{}개의 매치가 발견되었습니다. ({}개 파일 스킵: {}...)"
    RESULT_MSG_SKIPPED_SIMPLE = "{}개의 매치가 발견되었습니다. ({}개 파일 스킵)"
    RESULT_MSG_SKIPPED_WITH_SHEETS = "{}개의 매치가 발견되었습니다. ({}개 파일 스킵, {}개 시트 스킵)"
    RESULT_MSG_ONLY_SHEETS_SKIPPED = "{}개의 매치가 발견되었습니다. ({}개 시트 스킵)"
    LOG_SCH_SKIPPED_FILE_ITEM = "  └─ 스킵 된 파일: {} ({})"
    LOG_SCH_SKIPPED_SHEET_ITEM = "  └─ 스킵 된 시트: {} > {} ({})"
    MSG_LOG_LIMIT_REACHED = "[안내] 로그 표시 제한(5,000줄)에 도달하여 이전 로그를 정리했습니다."
    MSG_MATCH_TRUNCATION_NOTICE = "(검색 결과가 너무 많아 일부 상세 매치가 제한되었습니다)"
    MSG_BINARY_FILE = "[이진 파일]"
    MSG_BINARY_MATCH = "[이진 파일에서 {}개 항목 발견]"
    MSG_LONG_LINE_PREVIEW = "{}... (긴 줄)"
    SKIP_BADGE_TEMPLATE = "⚠️ 스킵: {}건 (로그 확인)"
    # [v5.1.0] Doctor Mode (자가 진단) 관련 문자열
    BTN_SYSTEM_DOCTOR = "시스템 자가 진단 실행"
    LOG_SYS_DOCTOR_TITLE = "시스템 자가 진단 보고서"
    LOG_SYS_DOCTOR_RUNNING = "시스템 자가 진단이 실행 중입니다. 잠시만 기다려 주세요..."
    LOG_SYS_DOCTOR_DONE = "자가 진단이 완료되었습니다. 보고서를 확인해 주세요."
    LOG_SYS_DOCTOR_FAIL = "자가 진단 보고서 생성 중 오류가 발생했습니다: {}"
    DOCTOR_CATEGORY_BASIC_INFO = "기본 시스템 정보"
    DOCTOR_CATEGORY_ENGINE = "검색 코어 엔진 무결성"
    DOCTOR_CATEGORY_HARDWARE = "하드웨어 가속 환경"
    DOCTOR_CATEGORY_PERMISSIONS = "저장 경로 및 파일 권한"
    DOCTOR_ITEM_OS = "운영체제(OS)"
    DOCTOR_ITEM_PYTHON = "Python 버전"
    DOCTOR_ITEM_APP_VERSION = "애플리케이션 버전"
    DOCTOR_ITEM_STATUS = "상태"
    DOCTOR_ITEM_DETAILS = "상세 내용"
    DOCTOR_ITEM_PROCESSOR = "프로세서(CPU)"
    DOCTOR_ITEM_64BIT = "64비트 아키텍처"
    DOCTOR_ITEM_CONFIG_DIR = "설정 데이터 저장 경로"
    DOCTOR_ITEM_WRITABLE = "쓰기 권한 상태"
    DOCTOR_STATUS_OK = "정상 (OK)"
    DOCTOR_STATUS_CRITICAL = "오류 (CRITICAL)"
    DOCTOR_STATUS_UNKNOWN = "확인 불가"
    DOCTOR_STATUS_WRITABLE = "정상 (쓰기 가능)"
    DOCTOR_STATUS_NOT_WRITABLE = "권한 없음 (쓰기 불가)"
    DOCTOR_STATUS_SUPPORTED = "지원"
    DOCTOR_STATUS_NOT_SUPPORTED = "미지원 (32비트)"
    DOCTOR_UNKNOWN = "알 수 없음"
    DOCTOR_ENGINE_LOADED = "Rust 고속 검색 가속 엔진이 성공적으로 로드되었습니다."
    DOCTOR_ENGINE_LOAD_FAILED = "Rust 엔진 로드 실패. 프로그램을 정상 구동할 수 없습니다. (원인: {})"
    DOCTOR_ENGINE_UNKNOWN_ERROR = "원인 미상"
    DOCTOR_ENGINE_CHECK_FAILED = "검색 엔진 상태 확인 중 예외 발생: {}"
    DOCTOR_REPORT_DATE = "진단 일시"
    DOCTOR_REPORT_FOOTER = "*StringFinder 시스템 자가 진단에서 생성됨*"
    RESULT_TABLE_TOOLTIP = "검색 결과 행을 더블 클릭하면 파일을 기본 프로그램으로 엽니다. (Ctrl+C: 경로 복사)"
    SKIP_EMPTY_FILE = "[건너뜀] 빈 파일"

    # 기존 검색 모드명 (안전성 확보를 위해 확인)
    SEARCH_MODE_EXACT = "내용 일치 검색"
    SEARCH_MODE_COMPLEX = "정밀 검색"
    BOOLEAN_SEARCH_MATCH_CONTENT = "[파일 내 일치하는 항목 존재]"
    # =========================================================================
    # [7] 내보내기 (Export)
    # =========================================================================
    RESULT_EXPORT_TITLE = "결과 내보내기"
    RESULT_EXPORT_FILTER = "엑셀 파일 (*.xlsx);;텍스트 파일 (*.txt)"
    RESULT_EXPORT_ALL = "전체 내보내기"
    EXPORT_TEXT_HEADER = "--- StringFinder 검색 결과 ---"
    EXPORT_TEXT_SEPARATOR = "-" * 80
    EXPORT_TEXT_LINE_PREFIX = "라인 {}: {}"
    EXPORT_SUMMARY_PREFIX = "요약: "
    EXCEL_SHEET_FILE_LIST = "검색 파일 목록"
    EXCEL_SHEET_MATCH_DETAILS = "검색 상세"
    HEADER_MATCH_COUNT = "매치 수"
    # =========================================================================
    # [8] 시스템 로그 (System Logs) - 형식: [시스템] 메시지
    # =========================================================================
    LOG_SYS_APP_STARTED_DECO = "--- 애플리케이션 시작 ---"
    LOG_SYS_APP_CLOSED = "--- 애플리케이션 종료 ---"
    LOG_SYS_SINGLE_INSTANCE_DETECTED = "[시스템] 중복 실행 시도 감지: 기존 창을 활성화합니다."
    LOG_SYS_SINGLE_INSTANCE_SERVER_START = "[시스템] 단일 인스턴스 서버 시작 완료: {}"
    LOG_SYS_SINGLE_INSTANCE_SERVER_START_FAIL = "[시스템] 단일 인스턴스 서버 시작 실패: {}"
    LOG_SYS_SINGLE_INSTANCE_REQUEST = "[시스템] 외부 인스턴스 활성화 요청 수신."
    LOG_SYS_SHUTDOWN = "[시스템] 애플리케이션 종료 중..."
    LOG_SYS_LOG_CLEANUP_DONE = "[시스템] 로그 파일 정리 완료 ({}개 제거)."
    LOG_SYS_RUST_SUCCESS = "[시스템] Rust 가속 엔진 로딩 완료."
    LOG_SYS_RUST_FALLBACK = "[시스템] Rust 엔진 로딩 실패: 애플리케이션을 시작할 수 없습니다."
    LOG_SYS_RUST_RUNTIME_FALLBACK = "[엔진] Rust 런타임 오류 발생 (Python 폴백 정책 미적용)."
    LOG_SYS_SMART_SCAN_FALLBACK = "[스캔] 스마트 스캔 오류 감지: Python 범용 스캔으로 전환합니다."
    LOG_SYS_WKR_SHUTDOWN = "[시스템] 워커 프로세스 종료 중..."
    LOG_SYS_WKR_SHUTDOWN_DONE = "[시스템] 워커 프로세스 종료 완료."
    LOG_SYS_WKR_SHUTDOWN_FAIL = "[시스템] 워커 프로세스 종료 실패: {}"
    LOG_SYS_SF_ENGINE_NOT_FOUND = "[시스템] Rust 라이브러리 유실 감지: {}"
    LOG_SYS_LOG_DIR_TEMP = "[시스템] 로그 폴더 생성 실패: 임시 경로를 사용합니다: {}"
    LOG_SYS_UNCAUGHT_EXCEPTION = "[시스템] 처리되지 않은 예외 발생."
    LOG_SYS_SCAN_WORKER_BROKEN = "[시스템] 스캔 워커 객체 손상 감지 (None)."
    LOG_SYS_QT_THREAD_WARNING = "[시스템] QThread 경고 발생: {}\n상세 스택:\n{}"
    LOG_SYS_CLI_ARGS_PARSE_FAIL = "[시스템] 명령어 인수 분석 실패: {}"
    LOG_SYS_DATA_DIR_CHECK_FAIL = "[시스템] 데이터 폴더 접근 실패: {}"
    LOG_SYS_CLEANUP_SKIP = "[시스템] 로그 정리 중단 ({}): {}"
    LOG_SYS_CLEANUP_ERROR = "[시스템] 종료 정리 작업 중 오류 발생: {}"
    TITLE_RUST_ENGINE_MISSING = "StringFinder — 엔진 로드 실패"
    MSG_RUST_ENGINE_MISSING = (
        "핵심 검색 엔진(Rust)을 불러올 수 없어 프로그램을 시작할 수 없습니다.\n\n"
        "해결 방법:\n"
        "  1. 'sf_engine.pyd' 파일이 프로그램 폴더에 존재하는지 확인하세요.\n"
        "  2. Microsoft Visual C++ 재배포 가능 패키지(x64)를 설치하세요.\n"
        "  3. 백신 소프트웨어가 해당 파일을 차단하고 있는지 확인하세요.\n\n"
        "문제가 지속되면 프로그램을 재설치하세요."
    )
    # 하위 호환용 (기존 참조가 있을 경우를 위해 유지)
    MSG_RUST_LOAD_FAIL = "[시스템] Rust 엔진 로딩 실패 (필수 요건 미충족)."
    MSG_RUST_LOAD_FAIL_GUIDE = MSG_RUST_ENGINE_MISSING
    MSG_QT_THREAD_DESTROYED = "[시스템] 스레드가 정상 종료 전 파괴되었습니다."
    MSG_QT_RESOURCE_LEAK = "[시스템] 애플리케이션 종료 시 일부 리소스 해제 실패."
    MSG_CRITICAL_ERROR_POPUP = (
        "[시스템] 치명적인 도구 오류 발생:\n\n{}\n\n상세 로그는 'crash_dump.txt'를 참조하세요."
    )
    LOG_SYS_CRITICAL_STOP_ALL = "[시스템] 치명적 오류 감지로 인한 모든 작업 강제 중단."
    LOG_SYS_TAB_STOP_FAIL = "[시스템] 탭 동작 중지 실패: {}"
    LOG_SYS_MEMORY_WARNING = "[시스템] 메모리 임계치 경고: {} (현재: {}%)"
    LOG_SYS_MEMORY_CHECK_FAIL = "[시스템] 시스템 리소스 확인 실패: {}"
    LOG_SYS_RUST_FAIL_MSG_UI_MISSING = "[안내] Rust 로드 실패 알림 중 UI 객체 참조 상실: {}"
    LOG_SYS_NO_TABS_TO_REMOVE = "[안내] 닫을 수 있는 활성 탭이 없습니다."
    LOG_SYS_CLEANUP_SIGNALER_FAIL = "[안내] 로깅 신호기 연결 해제 실패: {}"
    LOG_SYS_CLEANUP_DEFERRED = "[안내] 시스템 자원 정리 작업 지연됨."
    LOG_SYS_SINGLE_INSTANCE_LOCK_SUCCESS = "[시스템] 단일 인스턴스 배타적 락 획득: {}"
    # =========================================================================
    # [9] 설정 로그 (Config Logs) - 형식: [설정] 메시지
    # =========================================================================
    LOG_CFG_LOAD_FAIL = "[설정] 구성 로드 실패: 기본값을 사용합니다: {}"
    LOG_CFG_READ_ERROR = "[설정] 파일 읽기 실패: {}"
    LOG_CFG_SAVE_FAIL = "[설정] 구성 저장 실패: {}"
    LOG_CFG_SAVE_SHUTDOWN_FAIL = "[설정] 종료 시 최종 구성 저장 실패."
    LOG_CFG_SAVED = "[설정] 구성 파일 저장 완료: {}"
    LOG_CFG_SAVE_ERROR = "[설정] 구성 파일 저장 중 오류 발생: {} ({})"
    LOG_CFG_SAVE_RETRY = "[설정] 저장 재시도({}) 실패: {}"
    LOG_CFG_MIGRATE_WARN = (
        "[설정] 구성 파일 버전 상충 (파일: v{}, 앱: v{}): 일부 항목이 초기화될 수 있습니다."
    )
    LOG_CFG_DELETE_FAIL_MSG = "[설정] 구성 파일 삭제 실패: {}"
    LOG_CFG_LOG_CLEANUP_DONE_MSG = "[설정] 로그 파일 정리 완료 ({}개 삭제)."
    LOG_CFG_INVALID_VER = "[설정] 구성 버전 정보 무효: 기본 구성을 로컬에 적용합니다."
    LOG_CFG_MIGRATION = "[설정] 구성 마이그레이션 중: v{} -> v{}"
    LOG_CFG_APPDATA_FALLBACK = "[설정] 사용자 데이터 폴더 접근 실패({}): 임시 저장소로 전환합니다: {}"
    LOG_CFG_SESSION_DIR_CLEAR_FAIL = "[설정] 세션 폴더 정리 실패: {}"
    LOG_CFG_ALL_DATA_CLEARED = "[설정] 모든 로컬 데이터 초기화 완료."
    LOG_SES_SAVE_FAIL = "[세션] 세션 저장 실패 ('{}'): {}"
    LOG_SES_LOAD_FAIL = "[세션] 세션 로딩 실패 ('{}'): {}"
    LOG_SES_DELETE_FAIL = "[세션] 세션 삭제 실패 ('{}'): {}"
    LOG_SYS_STDERR_FLUSH_FAIL = "[시스템] 표준 에러 스트림 플러시 실패: {}"
    LOG_SYS_STARTUP_LOG_CLEANUP_FAIL = "[시스템] 시작 시 로그 파일 정리 실패: {}"
    LOG_SYS_CLOSE_CLEANUP_FAIL = "[시스템] 종료 시 리소스 정리 실패: {}"
    LOG_SYS_HANDLER_CLEANUP_FAIL = "[시스템] 클린업 핸들러 실행 오류: {}"
    LOG_SYS_CRITICAL_POPUP_FAIL = "[시스템] 치명적 오류 팝업 출력 실패: {}"
    LOG_SYS_LOG_CLEANUP_FAILURE = "[시스템] 로그 데이터 정리 실패: {}"
    LOG_SES_LIST_FAIL = "[세션] 세션 목록 조회 실패: {}"
    LOG_CFG_SESSION_TITLE_READ_FAIL = "[세션] 세션 제목 로딩 실패: {}"
    LOG_CFG_SESSION_SEARCH_FAIL = "[세션] 세션 데이터 탐색 중 오류 발생: {}"
    LOG_CFG_UNEXPECTED_LOAD_ERROR = "[설정] 알 수 없는 구성 로딩 오류: {}"
    LOG_CFG_BACKUP_CLEANUP_FAIL = "[설정] 백업 구성 파일 정리 실패: {}"
    LOG_CFG_TEMP_REMOVE_FAIL = "[설정] 임시 구성 파일 제거 실패: {}"
    LOG_SES_TEMP_CLEANUP_FAIL = "[세션] 임시 세션 데이터 정리 실패: {}"
    LOG_CFG_LOG_FILE_CLEANUP_FAIL = "[설정] 로그 파일 자동 정리 실패 ('{}'): {}"
    # =========================================================================
    # [10] 검색 및 스캔 로그 (Search & Scan Logs) - 형식: [검색 / 스캔 / 엔진] 메시지
    # =========================================================================
    LOG_SCH_STARTED = "=== [검색] 작업 시작 (초기화 중...) ==="
    LOG_SCH_ERROR_START = "[검색] 초기화 실패: {}"
    LOG_SCH_COND_QUERY = "  └─ 검색어: '{}'"
    LOG_SCH_COND_FOLDER = "  └─ 대상 폴더: {}"
    LOG_SCH_COND_FILENAME = "  └─ 파일명 필터: '{}'"
    LOG_SCH_COND_EXT = "  └─ 확장자 필터: '{}' (특수 모드: {})"
    LOG_SCH_PATH_ENTER = "=== [검색] 엔진 가동 ==="
    LOG_SCH_SCAN_DONE = "[스캔] 대상 파일 확보 완료: '{}'개 ({:.3f}초)."
    LOG_SCH_SCAN_DONE_WITH_SKIPPED = "[스캔] 대상 파일 확보 완료: {}개 (스킵: {}개, {:.3f}초)."
    LOG_SCH_SCAN_DONE_SIMPLE = "[스캔] 파일 스캔 완료 ({:.3f}초)."
    LOG_SCH_SCAN_STARTED_TYPE = "[스캔] 파일 스캔 시작 ({})..."
    LOG_SCH_SCAN_TYPE_RUST = "Rust 고속 경로"
    LOG_SCH_SCAN_TYPE_PYTHON = "Python 정밀 경로"
    LOG_SCH_SKIPPED_FILES_LIST = "[스캔] 검색 제외 대상 목록:"
    LOG_SCH_SCAN_DONE_FAST_PATH = "[스캔] 파일 스캔 완료 (고속 경로 적용)."
    LOG_SCH_SEARCH_DONE = "=== [검색] 작업 완료 (전체 소요 시간: {:.3f}초) ==="
    LOG_SCH_NO_FILES = "[검색] 검색 대상 파일이 없습니다."
    LOG_SCH_EMPTY_QUERY = "[검색] 검색어가 입력되지 않았습니다."
    LOG_SCH_FOLDER_ACCESS_DENIED = "[스캔] 폴더 접근 권한 거부: {} ({})"
    LOG_SCH_SCAN_OS_ERROR = "[스캔] 시스템 입출력 오류 발생: {} ({})"
    LOG_SCH_RUST_MODE = "[엔진] Rust 가속 모드 활성화 완료."
    LOG_SCH_PYTHON_MODE = "[엔진] Python 정밀 모드 활성화 완료."
    LOG_SCH_HYBRID_MODE = "[엔진] 하이브리드 모드(Rust + Python) 가동."
    LOG_SCH_STOP_REQUESTED = "[제어] 사용자 중지 요청 수신 중..."
    LOG_SCH_STOPPED_BY_USER = "[제어] 사용자에 의해 작업이 중지되었습니다."
    LOG_SCH_RESTART_PENDING = "[제어] 재시작 대기 중..."
    LOG_SCH_RESTART_SCHEDULED = "[제어] 재시작 예약됨."
    LOG_SCH_SKIP_COUNT = "[안내] 총 {}개 파일이 검색에서 제외되었습니다."
    LOG_SCH_SKIP_REASON = "  └─ '{}' (사유: {})"
    LOG_SCH_SKIP_SIMPLE = "  └─ '{}'"
    LOG_SCH_RETRY_PYTHON = "[엔진] Python 엔진으로 자동 재시도 중... ({})"
    LOG_SCH_ALL_FILES_GUIDE = "[안내] 전체 파일 스캔 모드."
    LOG_SCH_FILENAME_FILTER_GUIDE = "[안내] 파일명 필터 적용 완료: '{}'"
    LOG_SCH_SMART_SCAN_SKIPPED = "[스캔] 스마트 스캔 우회: '{}' (사유: {})"
    LOG_SCH_ALL_DONE = "=== [검색] 모든 작업이 종료되었습니다. (합계: {:.3f}초) ==="
    LOG_WKR_STARTED = "[엔진] 병렬 검색 데이터 처리 시작 ('{}' | 필터: {} | {})"
    LOG_WKR_RUNNING = "  └─ 현재 처리 중: {}개 파일..."
    LOG_WKR_PROGRESS = "  └─ 검색 진행률: {}% ({}/{})"
    LOG_WKR_COMPLEX_ACT = "[엔진] 유니코드 정밀 검색 모드(Python) 가동."
    LOG_WKR_PYTHON_ACT = "[엔진] Python 엔진 기반 검색 수행 중..."
    LOG_WKR_RUST_ACT = "[엔진] Rust 통합 엔진 활성화 중 (대상: {}개 경로)."
    LOG_WKR_DONE = "[엔진] 병렬 검색 처리 종료 (발견: {}, 매치: {}, {:.3f}초)."
    LOG_WKR_EXCEL_SCAN = "[엔진] Excel 구조 파일 검색 활성화."
    LOG_WKR_STOP_SIGNAL = "[워커] 작업 중단 신호 감지."
    LOG_WKR_ADAPTIVE_POLICY_INFO = "[워커] 적응형 자원 정책: 코어 {}개 중 {}개 워커 할당."
    # =========================================================================
    # [11] 리소스 및 성능 로그 (Resource & Performance) - 형식: [리소스 / 성능] 메시지
    # =========================================================================
    LOG_RES_DATA_DIR_FAIL = "[리소스] 데이터 폴더 열기 실패: {}"
    LOG_RES_LOG_CLEANUP_FAIL = "[리소스] 로그 데이터 정리 실패: {}"
    LOG_PERF_MANAGER_INIT = "[성능] 전역 멀티프로세싱 매니저 초기화 완료."
    LOG_PERF_MANAGER_FAIL = "[성능] 매니저 초기화 실패: {}"
    LOG_PERF_MANAGER_SHUTDOWN = "[성능] 전역 멀티프로세싱 매니저 종료 완료."
    LOG_EXECUTOR_SHUTDOWN_ERROR = "[성능] 실행기(Executor) 종료 중 오류 발생: {}"
    LOG_PERF_SKIP_RESIZE = "[성능] 대량 데이터({}) 행 감지: 자동 컬럼 폭 조절을 우회합니다."
    LOG_PERF_SKIP_MATCH_RESIZE = "[성능] 대량 매치({}) 행 감지: 상세 뷰 자동 폭 조절을 우회합니다."
    LOG_PERF_ADJUST_MATCH_FAIL = "[성능] 상세 컬럼 폭 조정 실패: {}"
    LOG_PERF_MANAGER_SHUTDOWN_ERROR = "[성능] 전역 멀티프로세싱 매니저 종료 중 예외 발생: {}"
    LOG_WKR_MANAGER_SHUTDOWN_IGNORED = "[워커] 전역 매니저 종료 무시 (채널 닫힘): {}"
    LOG_WKR_SIGNAL_EMIT_FAIL = "[워커] 상태 신호 전송 실패 ({}): {}"
    LOG_WKR_FUTURE_SCHEDULING_SKIPPED = "[워커] 작업 예약 건너뜀 (이미 중단): {}"
    LOG_WKR_FUTURE_SUBMISSION_FAIL = "[워커] 작업 제출(Future) 실패: {}"
    LOG_WKR_HANG_TIMEOUT = "[워커] 배치 작업 응답 시간 초과({}s): 강제 종료를 수행합니다."
    LOG_WKR_BATCH_FAILED = "[워커] 배치 작업 실행 실패: {}"
    LOG_WKR_EXECUTOR_SHUTDOWN_ERROR = "[워커] 실행기 리소스 해제 오류: {}"
    LOG_SYS_RUST_PATH = "[시스템] 로드된 Rust 엔진 경로: {}"
    LOG_SYS_RUST_HASH = "[시스템] Rust 엔진 무결성 체크(SHA-256): {}"
    LOG_SCH_RUST_PERF_STATS = "[성능] Rust 원시 통계: Count={}, Call={:.4f}s, Norm={:.4f}s"
    LOG_SCH_ENGINE_ISOLATION_BAIL = "[엔진] 고립 정책에 의한 작업 차단 (사유: {}): {}"
    LOG_SCH_RUST_SMART_SCAN_FATAL = "[오류] 스마트 스캔 중 치명적 예외 발생: {}"
    LOG_SCH_BINARY_COUNT_PARSE_FAIL = "[엔진] 바이너리 매치 카운트 분석 실패 (길이 {}): {}"
    LOG_SCH_EXISTENCE_DECODE_FAIL = "[엔진] 조기 존재 여부 확인 중 디코딩 실패: {}"
    LOG_SCH_EXISTENCE_JSON_FALLBACK = "[엔진] JSON 존재 확인 실패: 정밀 검색으로 폴백합니다. ('{}'): {}"
    LOG_SCH_EXISTENCE_UNEXPECTED = "[엔진] 일치 여부 확인 중 예기치 못한 오류 ('{}'): {}"
    LOG_SYS_RUST_NO_FALLBACK = "[시스템] Rust 엔진 로딩 실패 (Python 폴백 정책 미적용 환경)."
    # =========================================================================
    # [12] 에러 메시지 (Error Messages) - 형식: [오류] 메시지
    # =========================================================================
    ERROR_TITLE = "오류"
    ERROR_UNKNOWN = "알 수 없는 시스템 오류."
    ERROR_UNEXPECTED_FILE = "[오류] 파일 처리 중 예기치 못한 문제 발생 ('{}'): {}"
    ERROR_JSON_PARSE = "[오류] JSON 구문 분석 실패: {}"
    ERROR_EXPORT_FAIL = "[오류] 결과 내보내기 실패: {}"
    ERROR_OPEN_DIR_FAILED = "[오류] 폴더 열기 실패: {}"
    ERROR_IO_DURING_SEARCH = "[오류] 검색 수행 중 입출력 오류 발생: {}"
    ERROR_STOP_SEARCH_TAB = "[오류] 검색 탭 중단 처리 실패: {}"
    ERROR_EXCEL_ACCESS = "[오류] Excel 파일 접근 실패: {}"
    ERROR_EXCEL_SIGNATURE = "[오류] 유효하지 않은 Excel 서명입니다."
    ERROR_EXCEL_PROCESS = "[오류] Excel 데이터 변환 실패: {}"
    ERROR_EXCEL_CALAMINE = "[오류] Excel 검색을 위한 'python-calamine' 라이브러리가 유실되었습니다."
    ERROR_EXCEL_CALAMINE_REQ = "[오류] Excel 검색을 위한 'python-calamine' 라이브러리가 필요합니다."
    ERROR_EXCEL_LIB = "[오류] Excel 외부 라이브러리 연동 오류: {}"
    ERROR_SEARCH_EXCEL = "[오류] Excel 통합 검색 실패 ('{}'): {}"
    ERROR_SEARCH_EXCEL_SHEET = "[오류] Excel 시트 데이터 검색 실패 ('{}'): {}"
    ERROR_EXCEL_PANIC = "[오류] Excel 엔진 치명적 오류 (Panic): {}"
    ERROR_XML_PARSE = "[오류] XML 구문 분석 실패: {}"
    ERROR_FILE_ACCESS_BINARY = "[오류] 파일 바이너리 여부 확인 실패: {}"
    ERROR_READ_FILE = "[오류] 파일 본문 읽기 실패 ('{}'): {}"
    ERROR_SEARCH_CRITICAL_MSG = "검색 과정에서 치명적인 오류가 발생했습니다.\n로그 탭에서 상세 내용을 확인해주세요.\n\n원인: {}"
    ERROR_SESSION_SAVE = "[오류] 세션 데이터 보존 실패: {}"
    ERROR_LIMIT_REACHED = "[안내] 결과 임계치 도달: 도구 안정성을 위해 검색을 자동 중지했습니다. (최대 {}건)"
    ERROR_MEMORY_CRITICAL = "[안내] 메모리 고갈 위기: 시스템 보호를 위해 검색 작업을 강제 종료했습니다."
    ERROR_MEMORY_CRITICAL_TITLE = "메모리 부족으로 검색 중단"
    ERROR_MEMORY_CRITICAL_DETAIL = (
        "시스템 메모리 사용량이 높아 검색을 중단했습니다.\n\n"
        "다른 프로그램을 종료한 후 다시 시도하거나, 검색 범위와 결과 수를 줄여주세요."
    )
    TITLE_LIMIT_REACHED = "검색 제한 도달"
    MSG_RESULT_LIMIT_REACHED = "검색 결과가 도구 수용 범위를 초과하여(100,000건) 검색을 즉시 중지합니다.\n현재까지 발견된 결과만 표시됩니다."
    MSG_MATCH_LIMIT_PER_FILE = "(파일당 최대 매치 도달: {}건)"
    ERROR_NO_EXTENSION = "[안내] 검색을 위해 최소 하나 이상의 확장자를 선택해야 합니다."
    ERR_CRITICAL_SYSTEM = "[시스템] 치명적인 도구 내부 오류 발생: {}"
    LOG_SCH_BINARY_CHECK_FAIL = "[오류] 바이너리 확인 실패 ('{}'): {}"
    LOG_SCH_UNEXPECTED_ERROR = "[오류] 예기치 못한 도구 오류 발생 ('{}' : {}): {}"
    LOG_SCH_ERROR = "[오류] 검색 엔진 일반 오류: {}"
    LOG_SCH_RUST_ENGINE_ERROR = "[오류] Rust 코어 엔진 실행 오류 ('{}'): {}"
    LOG_SCH_RUST_JSON_FAIL = "[오류] Rust 기반 JSON 검색 실패 ('{}'): {}"
    LOG_SCH_RUST_DIR_SEARCH_ERROR = "[오류] Rust 디렉토리 탐색 오류 ('{}'): {}"
    LOG_SCH_JSON_LIMIT = "[오류] JSON 객체 구조 깊이 제한 초과."
    LOG_SCH_BINARY_CHECK_ERROR = "[오류] 바이너리 무결성 점검 오류: {}"
    LOG_SCH_RUST_DIR_FATAL = "[오류] Rust 디렉토리 검색 중 치명적 예외 ('{}'): {}"
    LOG_SCH_RUST_FILELIST_FATAL = "[오류] Rust 파일 목록 생성 중 치명적 예외 ('{}'): {}"
    LOG_SCH_RUST_SMART_SCAN_ERROR = "[오류] Rust 스마트 스캔 엔진 오류 ('{}'): {}"
    LOG_SRCH_RUST_MEM_GUARD_WARN = "[안내] Rust 엔진 메모리 보호 가드 작동: {}"
    LOG_SCH_ERROR_FILE = "[오류] 개별 파일 처리 실패 ('{}'): {}"
    LOG_SCH_RUST_EXCEL_FAIL = "[오류] Rust 기반 Excel 검색 실패 ('{}'): {}"
    LOG_SCH_JSON_FAIL = "[오류] Python 기반 JSON 검색 실패: {}"
    LOG_SCH_XML_FAIL = "[오류] Python 기반 XML 검색 실패: {}"
    LOG_SCH_RUST_XML_FAIL = "[오류] Rust 기반 XML 검색 실패 ('{}'): {}"
    LOG_SCH_STREAM_ERROR = "[오류] 데이터 스트림 처리 흐름 중단: {}"
    LOG_SCH_STOP_THREAD_ERR = "[오류] 작업 스레드 중지 처리 실패: {}"
    LOG_SCH_SEARCH_THREAD_ERROR = "[오류] 검색 스레드 종료 절차 중 오류 수신: {}"
    LOG_SCH_EXCEL_SHEET_ERROR_DETAIL = "[엔진] Excel 시트 분석 중 예외 발생: {}"
    LOG_SCH_EXCEL_ENGINE_PANIC_EXT = "[엔진] Excel 코어 패닉 감지 ('{}'): {}"
    LOG_SCH_EXCEL_ENGINE_PANIC = "[엔진] Excel 코어 치명적 패닉: {}"
    LOG_THEME_APPLY_FAIL = "[화면] 시각 테마 적용 실패 (테마={}): {}"
    ERROR_SORT_WORKER = "[오류] 데이터 정렬 워커(SortWorker) 동작 실패: {}"
    ERROR_GLOBAL_SORT_WORKER = "[오류] 전역 정렬 시스템(GlobalSortWorker) 오류: {}"
    LOG_WKR_BATCH_ERROR = "[워커] 배치 작업 단위 오류: {}"
    LOG_WORKER_ERROR_SIGNAL_FAIL = "[워커] 내부 오류 신호 전송 실패."
    LOG_WORKER_FINISH_SIGNAL_FAIL = "[워커] 내부 완료 신호 전송 실패."
    LOG_QT_INFO = "[Qt] 안내 메시지: {}"
    LOG_QT_WARNING = "[Qt] 경고 메시지: {}"
    LOG_QT_CRITICAL = "[Qt] 치명적 시스템 오류: {}"
    LOG_QT_FATAL = "[Qt] 프로세스 치명적 예외: {}"
    # =========================================================================
    # [13] 경로 스킵 사유 (Skip Reasons) - Prefix 포함
    # =========================================================================
    SKIP_REASON_WALK = "[오류] 폴더 트리 탐색 실패: {}"
    SKIP_REASON_OPEN = "[오류] 파일 열기 권한 없음: {}"
    SKIP_REASON_METADATA = "[오류] 파일 정보 읽기 실패: {}"
    SKIP_REASON_MMAP = "[오류] 메모리 맵(Mmap) 할당 실패: {}"
    SKIP_REASON_TOO_LARGE = "[안내] 파일 용량 제한 초과: {}"
    SKIP_REASON_MEMORY_GUARD = "[안내] 엔진 메모리 보호 작동: {}"
    SKIP_REASON_PANIC = "[오류] 하위 엔진 패닉 발생: {}"
    SKIP_REASON_CRITICAL = "[오류] 치명적인 예외 감지: {}"
    SKIP_REASON_UNKNOWN = "[오류] 상세 사유를 알 수 없는 스킵: {}"
