from sf_utils.app_strings import AppStrings


class Constants:
    APP_NAME = "StringFinder"
    APP_VERSION = AppStrings.APP_VERSION  # AppStrings에서 일원화 관리
    ENV_APPDATA = "APPDATA"
    APPDATA_FALLBACK_DIR = ".stringfinder"
    APPDATA_TEMP_DIR = "StringFinder_Temp"
    CONFIG_FILENAME = "config.json"
    SESSIONS_DIRNAME = "sessions"
    JSON_EXTENSION = ".json"
    LOG_FILE_GLOB = "*.log"
    TEMP_FILE_SUFFIX = ".tmp"
    BACKUP_FILE_SUFFIX = ".old"
    MAX_JSON_DOM_SIZE = 100 * 1024 * 1024  # 100MB (Python DOM 파싱 임계치)
    MAX_SMALL_FILE_SIZE = 10 * 1024 * 1024  # 10MB (소형 파일 전체 읽기 임계치)
    TYPE_SEARCH = "search"
    TYPE_FILENAME = "filename"
    TYPE_FOLDER = "folder"
    TYPE_EXT = "ext"
    TYPE_FILENAME_LIST = "filename_list"
    TYPE_FILENAME_FILTER = "filename_filter"
    VIEW_RESULT = "result"
    VIEW_MATCH = "match"
    ENC_UTF8 = "utf-8"
    ENC_UTF8_SIG = "utf-8-sig"
    ENC_UTF16 = "utf-16"
    ENC_UTF16_LE = "utf-16-le"
    ENC_UTF16_BE = "utf-16-be"
    ENC_EUCKR = "euc-kr"
    ENC_CP949 = "cp949"
    MODE_XML = "XML"
    MODE_JSON = "JSON"
    MODE_ARCHIVE = "Archive"
    MODE_EXCEL = "Excel"
    MODE_EXACT = AppStrings.SEARCH_MODE_EXACT
    MODE_COMPLEX = AppStrings.SEARCH_MODE_COMPLEX
    MODE_NORMAL = "Normal"
    EXT_XML = ".xml"
    EXT_JSON = ".json"
    EXT_ARCHIVE = ".archive"
    EXT_EXCEL = ("xlsx", "xlsm", "xls", "xlsb")
    DEFAULT_THEME = "Dark"
    DEFAULT_GLOBAL_HOTKEY = "alt+shift+space"
    RUST_MODE_NORMAL = 0
    RUST_MODE_JSON = 1 << 0
    RUST_MODE_XML = 1 << 1
    RUST_MODE_ARCHIVE = 1 << 2
    RUST_MODE_EXACT = 1 << 3
    RUST_MODE_EXCEL = 1 << 4
    RUST_MODE_EXCLUDE_BINARY = 1 << 5
    RUST_MODE_BOOLEAN_ONLY = 1 << 6
    KEY_CTRL = "ctrl"
    KEY_SHIFT = "shift"
    KEY_ALT = "alt"
    KEY_META = "meta"
    KEY_SPACE = "space"
    KEY_ESC = "esc"
    KEY_DELETE = "delete"
    KEY_BACKSPACE = "backspace"
    KEY_ENTER = "enter"
    KEY_TAB = "tab"
    KEY_UP = "up"
    KEY_DOWN = "down"
    KEY_LEFT = "left"
    KEY_RIGHT = "right"
    SYMBOL_CLOSE = "×"
    YIELD_SLEEP_TIME = 0.001
    HISTORY_ACTION_CLEAR = "action_clear"
    STATUS_SKIPPED = "SKIPPED"
    PAYLOAD_INPUTS = "inputs"
    PAYLOAD_RESULTS = "results"
    PAYLOAD_LOGS = "logs"
    PAYLOAD_TIMESTAMP = "timestamp"
    PAYLOAD_SUMMARY = "summary"
    STATE_KEY_SEARCH = "search"
    STATE_KEY_FILENAME = "filename"
    PAYLOAD_SEARCH_STRING = "search_string"
    PAYLOAD_SEARCH_PATHS = "search_paths"
    PAYLOAD_FILE_LIST = "file_list"
    PAYLOAD_SPECIAL_MODE = "special_mode"
    PAYLOAD_EXTENSIONS = "extensions"
    PAYLOAD_SKIPPED = "skipped"
    PAYLOAD_FILENAME_FILTER = "filename_filter"
    PAYLOAD_USE_COMPLEX_SEARCH = "use_complex_search"
    PAYLOAD_EXCLUDE_HIDDEN = "exclude_hidden"
    PAYLOAD_EXCLUDE_BINARY = "exclude_binary"
    CONFIG_KEY_VERSION = "config_version"
    CONFIG_KEY_FILTERS = "filters"
    CONFIG_KEY_FOLDERS = "folders"
    CONFIG_KEY_EXTENSIONS = "extensions"
    CONFIG_KEY_FILENAMES = "filenames"
    CONFIG_KEY_HISTORY = "history"
    CONFIG_KEY_FILENAME_HISTORY = "filename_history"
    CONFIG_KEY_GEOMETRY = "geometry"
    CONFIG_KEY_WINDOW_STATE = "windowState"
    CONFIG_KEY_MAIN_SPLITTER_STATE = "main_splitter_state"
    CONFIG_KEY_RESULT_SPLITTER_STATE = "result_splitter_state"
    CONFIG_KEY_FILTER_SPLITTER_STATE = "filter_splitter_state"
    CONFIG_KEY_THEME = "theme"
    CONFIG_KEY_GLOBAL_HOTKEY = "global_hotkey"
    CONFIG_KEY_RUN_AT_STARTUP = "run_at_startup"
    CONFIG_KEY_CLOSE_TO_TRAY = "close_to_tray"
    CONFIG_KEY_CASE_INSENSITIVE = "case_insensitive"
    CONFIG_KEY_EXCLUDE_BINARY = "exclude_binary"
    CONFIG_KEY_RESULT_COLUMN_WIDTHS = "result_column_widths"
    CONFIG_KEY_MATCH_COLUMN_WIDTHS = "match_column_widths"
    CONFIG_KEY_LOG_RETENTION = "log_retention"
    CONFIG_KEY_LOG_RETENTION_ENABLED = "enabled"
    CONFIG_KEY_LOG_RETENTION_MAX_FILES = "max_files"
    CONFIG_KEY_LOG_RETENTION_MAX_DAYS = "max_days"
    CONFIG_KEY_DOCK_LAYOUT_STATE = "dock_layout_state"
    CONFIG_KEY_LOCK_DOCK_LAYOUT = "lock_dock_layout"
    CONFIG_KEY_TABS = "tabs"
    OBJ_NAME_SEARCH_DOCK = "SearchDock"
    OBJ_NAME_FOLDER_DOCK = "FolderDock"
    OBJ_NAME_EXT_DOCK = "ExtDock"
    OBJ_NAME_FILENAME_DOCK = "FilenameDock"
    COLOR_RED = "#FF5555"
    THRESHOLD_LARGE_FILE = 100 * 1024 * 1024  # 대용량 기준(100MB)
    BATCH_SIZE_LARGE = 500
    BATCH_SIZE_NORMAL = 100
    TIMEOUT_WORKER_HANG = 600
    MAX_TOTAL_MATCHES = 500_000  # 글로벌 매치 상한 (50만 건)
    MAX_PER_FILE_MATCHES = 5_000  # 파일당 매치 상한 (5천 명)
    MEMORY_THRESHOLD_PERCENT = 85  # 메모리 사용량 임계값 (%)

    # Rust 엔진 결과 배치 크기 및 지연 간격 (성능 튜닝용)
    RUST_RESULT_BATCH_SIZE = 128
    RUST_RESULT_FLUSH_MS = 75

    class SearchState:
        IDLE = "IDLE"
        SCANNING = "SCANNING"
        SEARCHING = "SEARCHING"
        STOPPING = "STOPPING"
