"""English translations for :mod:`sf_utils.app_strings`."""


ENGLISH_STRINGS = {
    "TITLE_CRITICAL_ERROR": "StringFinder Error",
    "TITLE_QT_WARNING": "Thread Warning",
    "ERROR_DETAIL_FORMAT": "Error details:\n{}",
    "ERROR_RUST_API_VERSION": "API version mismatch: required={}, actual={}",
    "ERROR_UNCLOSED_QUOTE": "An unmatched quotation mark was found.",
    "STATUS_ELAPSED_TIME": "Elapsed: {:02d}:{:02d}",
    "MSG_SEARCH_SINGLE_CHAR_WARN": "The search term is very short and may take a long time. Continue?",
    "MSG_ALREADY_RUNNING": "The application is already running.",
    "MSG_SEARCH_BLOCKED_BY_OTHER_TAB": "A search is running in another tab. Try again after it finishes.",
    "SEARCH_LABEL": "Search text",
    "ADD_FOLDER_BTN": "Add folder",
    "ADD_EXT_BTN": "Add",
    "SELECT_ALL_BTN": "Select all",
    "DESELECT_ALL_BTN": "Clear all",
    "BTN_CLOSE": "Close",
    "SEARCH_BTN": "Search",
    "SEARCH_BTN_STOP": "Stop",
    "SEARCH_BTN_STOPPING": "Stopping...",
    "OPEN_FILE": "Open file",
    "OPEN_FOLDER": "Open folder",
    "OPEN_LINE_IN_EDITOR": "Open line",
    "COPY_PATH": "Copy path (Ctrl+C)",
    "COPY_CONTENT": "Copy content (Ctrl+C)",
    "LOG_FILTER_LABEL": "Log filter:",
    "LOG_CLEAR_BTN": "Clear logs",
    "FILENAME_FILTER_LABEL": "Filename filter:",
    "SELECT_FOLDER_TITLE": "Select folder",
    "PAGINATION_PREV": "Previous",
    "PAGINATION_NEXT": "Next",
    "PAGINATION_PAGE": "Page:",
    "PAGINATION_DISPLAY": "Show:",
    "SUCCESS_TITLE": "Success",
    "INFO_TITLE": "Information",
    "INFO_CLEAR_SUCCESS": "The data was deleted successfully.",
    "INFO_RESET_LAYOUT_DONE": "The layout has been reset.",
    "INFO_LOGS_DELETED": "The logs have been deleted.",
    "HISTORY_CLEAR_ALL": "--- Clear history ---",
    "DOCK_SEARCH_TITLE": "Search settings",
    "DOCK_FOLDER_TITLE": "Folders (including subfolders)",
    "DOCK_EXT_TITLE": "Extensions",
    "DOCK_FILENAME_TITLE": "Filename filter",
    "DOCK_RESULT_TITLE": "Search results",
    "MENU_LOCK_LAYOUT": "Lock layout",
    "MENU_RESET_LAYOUT": "Reset layout",
    "TAB_RENAME_TITLE": "Rename tab",
    "TAB_RENAME_PROMPT": "Enter a new tab name:",
    "TAB_CLOSE_MENU": "Close tab",
    "SEARCH_TAB_DEFAULT_TITLE": "Search",
    "TAB_RESULTS": "Search results",
    "TAB_LOGS": "Logs",
    "SETTINGS_TITLE": "Settings",
    "SETTINGS_GROUP_GENERAL": "General",
    "SETTINGS_GROUP_APPEARANCE": "Appearance",
    "SETTINGS_GROUP_LOG": "Logs",
    "SETTINGS_GROUP_DATA": "Data",
    "SETTINGS_GROUP_ADVANCED": "Advanced",
    "EXTERNAL_EDITOR_GROUP": "Open line with",
    "EXTERNAL_EDITOR_LABEL": "Application:",
    "EXTERNAL_EDITOR_SYSTEM": "System default application",
    "EXTERNAL_EDITOR_CUSTOM": "Custom",
    "EXTERNAL_EDITOR_PATH_LABEL": "Executable:",
    "EXTERNAL_EDITOR_ARGS_LABEL": "Argument format:",
    "EXTERNAL_EDITOR_ARGS_PLACEHOLDER": "Example: --line {line} {file}",
    "EXTERNAL_EDITOR_BROWSE": "Browse",
    "EXTERNAL_EDITOR_FILE_FILTER": "Executables (*.exe);;All files (*)",
    "ADVANCED_MAX_TOTAL_MATCHES": "Maximum total matches",
    "ADVANCED_MAX_PER_FILE_MATCHES": "Maximum matches per file",
    "ADVANCED_MAX_JSON_DOM_SIZE": "Structured-search file size safety limit",
    "ADVANCED_MAX_JSON_DOM_SIZE_DESCRIPTION": "This input-file size limit applies to all JSON searches and precise XML searches. It does not apply to default Rust XML searches.",
    "ADVANCED_PRECISE_SEARCH_GROUP": "Precise-search processing thresholds",
    "ADVANCED_PRECISE_SEARCH_DESCRIPTION": "The following three settings apply only to the Python path used by precise search, not to the default Rust search.",
    "ADVANCED_MAX_SMALL_FILE_SIZE": "Small-text-file path threshold",
    "ADVANCED_MAX_SMALL_FILE_SIZE_DESCRIPTION": "Plain-text files below this size use the small-file path with a 64 KB encoding sample and line-by-line search.",
    "ADVANCED_JSON_MMAP_THRESHOLD": "JSON mmap read threshold",
    "ADVANCED_JSON_MMAP_THRESHOLD_DESCRIPTION": "JSON files at or above this size are read through mmap, but the entire document is still parsed as JSON.",
    "ADVANCED_TIMEOUT_WORKER_HANG": "Precise-search batch completion timeout",
    "ADVANCED_TIMEOUT_WORKER_HANG_DESCRIPTION": "Terminates the entire Python worker pool if no file batch completes within this time during precise search.",
    "ADVANCED_MAX_CHECK_CELLS": "Maximum Excel cells checked in existence mode",
    "ADVANCED_MAX_CHECK_CELLS_DESCRIPTION": "Maximum cells checked per file in existence-only mode. Reaching the limit is reported as a partial search for that file.",
    "ADVANCED_MAX_JSON_DEPTH": "Maximum JSON nesting depth",
    "TOOLTIP_MAX_TOTAL_MATCHES": "Maximum number of matches displayed for one search across the application.",
    "TOOLTIP_MAX_PER_FILE_MATCHES": "Maximum results allowed in one file. Excess matches are limited with a warning.",
    "TOOLTIP_MAX_JSON_DOM_SIZE": "JSON files larger than this are not parsed deeply to prevent out-of-memory errors.",
    "TOOLTIP_MAX_SMALL_FILE_SIZE": "Files below this size are read directly instead of using mmap for faster searches.",
    "TOOLTIP_JSON_MMAP_THRESHOLD": "JSON files above this size use an mmap-based streaming parser to conserve RAM.",
    "TOOLTIP_TIMEOUT_WORKER_HANG": "Terminates a single-file search process if it remains unresponsive for this duration.",
    "TOOLTIP_MAX_CHECK_CELLS": "Maximum empty cells checked in existence-only mode to prevent indefinite delays.",
    "TOOLTIP_MAX_JSON_DEPTH": "Maximum nesting depth used to prevent stack overflows in abnormally deep JSON documents.",
    "UNIT_COUNT": "items",
    "UNIT_SEC": "sec",
    "UNIT_CELL": "cells",
    "UNIT_DEPTH": "levels",
    "BTN_RESET_ADVANCED": "Restore advanced defaults",
    "LANGUAGE_LABEL": "Language:",
    "LANGUAGE_RESTART_REQUIRED": "The language change will take effect after restarting the application.",
    "THEME_LABEL": "Theme:",
    "THEME_DARK": "Dark",
    "THEME_LIGHT": "Light",
    "LOG_RETENTION_LABEL": "Log retention:",
    "BTN_DELETE_ALL_LOGS": "Delete all logs",
    "MSG_DELETE_LOGS_CONFIRM": "Delete all log files?",
    "MAX_FILES_LABEL": "Maximum files:",
    "MAX_DAYS_LABEL": "Maximum retention days:",
    "OPEN_DATA_DIR_BTN": "Open data folder",
    "CLEAR_ALL_DATA_BTN": "Delete all data",
    "CLEAR_ALL_DATA_CONFIRM": "Delete all settings and history?",
    "COMBO_ENABLE": "Enabled",
    "COMBO_DISABLE": "Disabled",
    "COMBO_LOCKED": "Locked",
    "COMBO_UNLOCKED": "Unlocked",
    "COMPLEX_SEARCH_LABEL": " (slower)",
    "COMPLEX_SEARCH_TOOLTIP": (
        "Searches complex Unicode variants beyond common English, Korean, and symbols.\n"
        "Examples: German (ß↔ss), French (Œ↔oe), enclosed characters (㉮↔가), and other variants.\n"
        "This provides a deeper search at the cost of speed."
    ),
    "EXCLUDE_HIDDEN_LABEL": "Exclude hidden files/folders",
    "EXCLUDE_HIDDEN_TOOLTIP": (
        "Excludes files and folders with the Windows Hidden attribute.\n"
        "Avoiding unnecessary locations such as .git, node_modules, and AppData greatly improves speed."
    ),
    "EXCLUDE_BINARY_LABEL": "Exclude binary files",
    "EXCLUDE_BINARY_TOOLTIP": (
        "Excludes binary files such as images and executables (exe, dll).\n"
        "Required special formats such as Excel and explicitly selected extensions remain included."
    ),
    "BOOLEAN_SEARCH_LABEL": "Existence only (fast)",
    "BOOLEAN_SEARCH_TOOLTIP": (
        "Checks only whether the text exists in each file.\n"
        "The search moves to the next file after the first match, making it very fast.\n"
        "Detailed matches such as line numbers are not provided."
    ),
    "SPECIAL_SEARCH_LABEL": "Special search:",
    "SPECIAL_SEARCH_OFF": "Off",
    "SPECIAL_SEARCH_ITEMS": [
        "Off",
        "XML (contains)",
        "XML (exact)",
        "JSON (contains)",
        "JSON (exact)",
        "Excel (contains)",
        "Excel (exact)",
    ],
    "SPECIAL_SEARCH_XML": "XML (contains)",
    "SPECIAL_SEARCH_JSON": "JSON (contains)",
    "SPECIAL_SEARCH_EXCEL": "Excel (contains)",
    "SEARCH_EDIT_PLACEHOLDER": "Enter text to search for... (Use Deep search for complex Unicode variants)",
    "EXT_EDIT_PLACEHOLDER": "Extension (for example: txt)",
    "FILENAME_EDIT_PLACEHOLDER": "Filename filter (for example: npc, fo / comma-separated)...",
    "FILENAME_LIST_PLACEHOLDER": "Filter term (for example: npc)",
    "RESULT_FILTER_FILE_PLACEHOLDER": "Filter files...",
    "RESULT_FILTER_FOLDER_PLACEHOLDER": "Filter folders...",
    "MATCH_FILTER_LIST_PLACEHOLDER": "Filter list...",
    "MATCH_FILTER_LINE_PLACEHOLDER": "Filter lines...",
    "MATCH_FILTER_CONTENT_PLACEHOLDER": "Filter content...",
    "MATCH_FILTER_NAME_PLACEHOLDER": "Filter names...",
    "MATCH_FILTER_KEY_PLACEHOLDER": "Filter keys...",
    "MATCH_FILTER_VALUE_PLACEHOLDER": "Filter values...",
    "MATCH_FILTER_EXCEL_SHEET_PLACEHOLDER": "Filter sheets...",
    "MATCH_FILTER_EXCEL_CELL_PLACEHOLDER": "Filter cells...",
    "MATCH_FILTER_EXCEL_VAL_PLACEHOLDER": "Filter values...",
    "HEADER_COUNT": "Count",
    "HEADER_FOLDER": "Folder",
    "HEADER_FILE": "File",
    "HEADER_POSITION": "Position",
    "HEADER_CONTENT": "Content",
    "HEADER_JSON_KEY": "Key",
    "HEADER_JSON_VALUE": "Value",
    "HEADER_XML_NAME": "Key",
    "HEADER_XML_VALUE": "Value",
    "HEADER_EXCEL_SHEET": "Sheet",
    "HEADER_EXCEL_CELL": "Cell",
    "HEADER_EXCEL_VALUE": "Value",
    "HEADER_LIST": "List",
    "STATUS_READY": "Ready",
    "STATUS_IDLE": "Idle",
    "STATUS_SCANNING": "Scanning files...",
    "STATUS_SEARCHING": "Searching text...",
    "STATUS_STOPPING": "Stopping...",
    "STATUS_FOUND_COUNT": "Search completed in {} files",
    "STATUS_ERROR_PREFIX": "[Error] ",
    "RESULT_SUMMARY_TEMPLATE": "Found: {} files | Matches: {}",
    "RESULT_EMPTY_MSG": "Start a search to see results.",
    "RESULT_SEARCHING_MSG": "Searching for \"{}\"...",
    "RESULT_EMPTY_NO_FOLDER": "Add a folder to search.",
    "RESULT_EMPTY_NO_MATCH": "No results found for '{}'. Use Deep search if text may have been missed.",
    "RESULT_SUMMARY_FORMAT": "Files containing text: {file_count} | Total matches: {match_count} | Time: {duration}s",
    "SKIPPED_FILES_COUNT": "⚠ Skipped files: {}",
    "SKIPPED_FILES_VIEW_BUTTON": "View file list",
    "SKIPPED_FILES_DIALOG_TITLE": "Skipped files",
    "SKIPPED_FILES_COPY_BUTTON": "Copy entire list",
    "SKIPPED_FILES_CLOSE_BUTTON": "Close",
    "SKIPPED_FILES_COPIED": "Copied to the clipboard.",
    "SKIPPED_FILES_REASON": "Reason: {}",
    "SKIPPED_FILES_DETAILS_MISSING": "Files without recorded details: {}",
    "SELECTED_FILE_INFO_TEMPLATE": "📄 {}  ({} total matches)",
    "CONTEXT_PREVIEW_TITLE": "Context preview",
    "CONTEXT_PREVIEW_BEFORE_LABEL": "Before:",
    "CONTEXT_PREVIEW_AFTER_LABEL": "After:",
    "CONTEXT_PREVIEW_LINE_UNIT": "lines",
    "CONTEXT_PREVIEW_PLACEHOLDER": "Select a match to view its surrounding context.",
    "CONTEXT_PREVIEW_FILE_UNAVAILABLE": "[The file does not exist or cannot be accessed]",
    "CONTEXT_PREVIEW_LOADING": "Loading context...",
    "CONTEXT_PREVIEW_SPECIAL_MATCH": "[Special data match]\n\nPosition: {}\nContent: {}",
    "CONTEXT_PREVIEW_EXCEL_MATCH": "[Excel cell match]\n\nSheet: {}\nCell: {}\nValue: {}",
    "CONTEXT_PREVIEW_EXCEL_VALUE_TRUNCATED": "\n[The cell value is long; only part is displayed]",
    "CONTEXT_PREVIEW_READ_FAILED": "[Failed to read context preview]\n{}",
    "CONTEXT_PREVIEW_SCAN_LIMIT": (
        "[Context preview skipped]\nThe target line is too far away, so reading was stopped to protect the UI."
    ),
    "CONTEXT_PREVIEW_TRUNCATED": "\n[Long context; only part is displayed]",
    "SUMMARY_PREFIX_SEARCHING": "[Searching] ",
    "SUMMARY_PREFIX_STOPPED": "[Search stopped] ",
    "SUMMARY_PREFIX_FINISHED": "[Search complete] ",
    "RESULT_MSG_SKIPPED_DETAILS": "{} matches found. ({} files skipped: {}...)",
    "RESULT_MSG_SKIPPED_SIMPLE": "{} matches found. ({} files skipped)",
    "RESULT_MSG_SKIPPED_WITH_SHEETS": "{} matches found. ({} files skipped, {} sheets skipped)",
    "RESULT_MSG_ONLY_SHEETS_SKIPPED": "{} matches found. ({} sheets skipped)",
    "LOG_SCH_SKIPPED_FILE_ITEM": "  └─ Skipped file: {} ({})",
    "LOG_SCH_SKIPPED_SHEET_ITEM": "  └─ Skipped sheet: {} > {} ({})",
    "MSG_LOG_LIMIT_REACHED": "[Info] The 5,000-line log display limit was reached; older logs were cleared.",
    "MSG_MATCH_TRUNCATION_NOTICE": "(Some detailed matches were limited because too many results were found)",
    "MSG_BINARY_FILE": "[Binary file]",
    "MSG_BINARY_MATCH": "[{} items found in binary file]",
    "MSG_LONG_LINE_PREVIEW": "{}... (long line)",
    "SKIP_BADGE_TEMPLATE": "⚠️ Skipped: {} (check logs)",
    "BTN_SYSTEM_DOCTOR": "Run system diagnostics",
    "LOG_SYS_DOCTOR_TITLE": "System Diagnostic Report",
    "LOG_SYS_DOCTOR_RUNNING": "System diagnostics are running. Please wait...",
    "LOG_SYS_DOCTOR_DONE": "Diagnostics completed. Please review the report.",
    "LOG_SYS_DOCTOR_FAIL": "An error occurred while creating the diagnostic report: {}",
    "DOCTOR_CATEGORY_BASIC_INFO": "Basic system information",
    "DOCTOR_CATEGORY_ENGINE": "Search core integrity",
    "DOCTOR_CATEGORY_HARDWARE": "Hardware acceleration environment",
    "DOCTOR_CATEGORY_PERMISSIONS": "Storage paths and file permissions",
    "DOCTOR_ITEM_OS": "Operating system",
    "DOCTOR_ITEM_PYTHON": "Python version",
    "DOCTOR_ITEM_APP_VERSION": "Application version",
    "DOCTOR_ITEM_STATUS": "Status",
    "DOCTOR_ITEM_DETAILS": "Details",
    "DOCTOR_ITEM_PROCESSOR": "Processor (CPU)",
    "DOCTOR_ITEM_64BIT": "64-bit architecture",
    "DOCTOR_ITEM_CONFIG_DIR": "Settings data path",
    "DOCTOR_ITEM_WRITABLE": "Write permission",
    "DOCTOR_STATUS_OK": "Normal (OK)",
    "DOCTOR_STATUS_CRITICAL": "Error (CRITICAL)",
    "DOCTOR_STATUS_UNKNOWN": "Unavailable",
    "DOCTOR_STATUS_WRITABLE": "Normal (writable)",
    "DOCTOR_STATUS_NOT_WRITABLE": "No permission (not writable)",
    "DOCTOR_STATUS_SUPPORTED": "Supported",
    "DOCTOR_STATUS_NOT_SUPPORTED": "Unsupported (32-bit)",
    "DOCTOR_UNKNOWN": "Unknown",
    "DOCTOR_ENGINE_LOADED": "The Rust high-speed search engine loaded successfully.",
    "DOCTOR_ENGINE_LOAD_FAILED": "Failed to load the Rust engine. The application cannot run normally. (Cause: {})",
    "DOCTOR_ENGINE_UNKNOWN_ERROR": "Unknown cause",
    "DOCTOR_ENGINE_CHECK_FAILED": "An exception occurred while checking search engine status: {}",
    "DOCTOR_REPORT_DATE": "Diagnostic date",
    "DOCTOR_REPORT_FOOTER": "*Generated by StringFinder system diagnostics*",
    "RESULT_TABLE_TOOLTIP": "Double-click a result row to open the file in its default application. (Ctrl+C: copy path)",
    "SKIP_EMPTY_FILE": "[Skipped] Empty file",
    "SEARCH_MODE_EXACT": "exact",
    "SEARCH_MODE_COMPLEX": "Deep search",
    "BOOLEAN_SEARCH_MATCH_CONTENT": "[Matching item exists in file]",
    "RESULT_EXPORT_TITLE": "Export results",
    "RESULT_EXPORT_FILTER": "Excel files (*.xlsx);;Text files (*.txt)",
    "RESULT_EXPORT_ALL": "Export all",
    "EXPORT_TEXT_HEADER": "--- StringFinder Search Results ---",
    "EXPORT_TEXT_LINE_PREFIX": "Line {}: {}",
    "EXPORT_SUMMARY_PREFIX": "Summary: ",
    "EXCEL_SHEET_FILE_LIST": "Searched files",
    "EXCEL_SHEET_MATCH_DETAILS": "Match details",
    "HEADER_MATCH_COUNT": "Matches",
    "LOG_SYS_APP_STARTED_DECO": "--- Application started ---",
    "LOG_SYS_APP_CLOSED": "--- Application closed ---",
    "LOG_SYS_SINGLE_INSTANCE_DETECTED": "[System] Another launch was detected; activating the existing window.",
    "LOG_SYS_SINGLE_INSTANCE_SERVER_START": "[System] Single-instance server started: {}",
    "LOG_SYS_SINGLE_INSTANCE_SERVER_START_FAIL": "[System] Failed to start single-instance server: {}",
    "LOG_SYS_SINGLE_INSTANCE_REQUEST": "[System] Received an external instance activation request.",
    "LOG_SYS_SHUTDOWN": "[System] Shutting down the application...",
    "LOG_SYS_LOG_CLEANUP_DONE": "[System] Log cleanup completed ({} removed).",
    "LOG_SYS_RUST_SUCCESS": "[System] Rust acceleration engine loaded.",
    "LOG_SYS_RUST_FALLBACK": "[System] Failed to load the Rust engine; the application cannot start.",
    "LOG_SYS_RUST_RUNTIME_FALLBACK": "[Engine] A Rust runtime error occurred (Python fallback is disabled by policy).",
    "LOG_SYS_SMART_SCAN_FALLBACK": "[Scan] Smart-scan error detected; switching to the general Python scanner.",
    "LOG_SYS_WKR_SHUTDOWN": "[System] Shutting down worker processes...",
    "LOG_SYS_WKR_SHUTDOWN_DONE": "[System] Worker processes shut down.",
    "LOG_SYS_WKR_SHUTDOWN_FAIL": "[System] Failed to shut down worker processes: {}",
    "LOG_SYS_SF_ENGINE_NOT_FOUND": "[System] Rust library is missing: {}",
    "LOG_SYS_LOG_DIR_TEMP": "[System] Failed to create the log folder; using a temporary path: {}",
    "LOG_SYS_UNCAUGHT_EXCEPTION": "[System] An unhandled exception occurred.",
    "LOG_SYS_SCAN_WORKER_BROKEN": "[System] Invalid scan worker object detected (None).",
    "LOG_SYS_QT_THREAD_WARNING": "[System] QThread warning: {}\nStack details:\n{}",
    "LOG_SYS_CLI_ARGS_PARSE_FAIL": "[System] Failed to parse command-line arguments: {}",
    "LOG_SYS_DATA_DIR_CHECK_FAIL": "[System] Failed to access the data folder: {}",
    "LOG_SYS_CLEANUP_SKIP": "[System] Log cleanup stopped ({}): {}",
    "LOG_SYS_CLEANUP_ERROR": "[System] An error occurred during shutdown cleanup: {}",
    "TITLE_RUST_ENGINE_MISSING": "StringFinder — Engine Load Failed",
    "MSG_RUST_ENGINE_MISSING": (
        "StringFinder cannot start because the core Rust search engine could not be loaded.\n\n"
        "Try the following:\n"
        "  1. Confirm that 'sf_engine.pyd' exists in the application folder.\n"
        "  2. Install the Microsoft Visual C++ Redistributable (x64).\n"
        "  3. Check whether antivirus software blocked the file.\n\n"
        "Reinstall the application if the problem continues."
    ),
    "MSG_RUST_LOAD_FAIL": "[System] Failed to load the Rust engine (required dependency unavailable).",
    "MSG_RUST_LOAD_FAIL_GUIDE": (
        "StringFinder cannot start because the core Rust search engine could not be loaded.\n\n"
        "Try the following:\n"
        "  1. Confirm that 'sf_engine.pyd' exists in the application folder.\n"
        "  2. Install the Microsoft Visual C++ Redistributable (x64).\n"
        "  3. Check whether antivirus software blocked the file.\n\n"
        "Reinstall the application if the problem continues."
    ),
    "MSG_QT_THREAD_DESTROYED": "[System] A thread was destroyed before it shut down normally.",
    "MSG_QT_RESOURCE_LEAK": "[System] Some resources could not be released during application shutdown.",
    "MSG_CRITICAL_ERROR_POPUP": "[System] A critical application error occurred:\n\n{}\n\nSee 'crash_dump.txt' for details.",
    "LOG_SYS_CRITICAL_STOP_ALL": "[System] All tasks were forcibly stopped after a critical error.",
    "LOG_SYS_TAB_STOP_FAIL": "[System] Failed to stop tab activity: {}",
    "LOG_SYS_MEMORY_WARNING": "[System] Memory threshold warning: {} (current: {}%)",
    "LOG_SYS_MEMORY_CHECK_FAIL": "[System] Failed to check system resources: {}",
    "LOG_SYS_RUST_FAIL_MSG_UI_MISSING": "[Info] UI reference was lost while reporting a Rust load failure: {}",
    "LOG_SYS_NO_TABS_TO_REMOVE": "[Info] There is no active tab that can be closed.",
    "LOG_SYS_CLEANUP_SIGNALER_FAIL": "[Info] Failed to disconnect the logging signaler: {}",
    "LOG_SYS_CLEANUP_DEFERRED": "[Info] System resource cleanup was deferred.",
    "LOG_SYS_SINGLE_INSTANCE_LOCK_SUCCESS": "[System] Acquired the single-instance lock: {}",
    "LOG_CFG_LOAD_FAIL": "[Settings] Failed to load configuration; using defaults: {}",
    "LOG_CFG_READ_ERROR": "[Settings] Failed to read the file: {}",
    "LOG_CFG_SAVE_FAIL": "[Settings] Failed to save configuration: {}",
    "LOG_CFG_SAVE_SHUTDOWN_FAIL": "[Settings] Failed to save the final configuration during shutdown.",
    "LOG_CFG_SAVED": "[Settings] Configuration saved: {}",
    "LOG_CFG_SAVE_ERROR": "[Settings] Error while saving configuration: {} ({})",
    "LOG_CFG_SAVE_RETRY": "[Settings] Save retry {} failed: {}",
    "LOG_CFG_MIGRATE_WARN": "[Settings] Configuration version mismatch (file: v{}, app: v{}); some values may reset.",
    "LOG_CFG_DELETE_FAIL_MSG": "[Settings] Failed to delete the configuration file: {}",
    "LOG_CFG_LOG_CLEANUP_DONE_MSG": "[Settings] Log cleanup completed ({} deleted).",
    "LOG_CFG_INVALID_VER": "[Settings] Invalid configuration version; applying local defaults.",
    "LOG_CFG_MIGRATION": "[Settings] Migrating configuration: v{} -> v{}",
    "LOG_CFG_APPDATA_FALLBACK": "[Settings] User data folder access failed ({}); using temporary storage: {}",
    "LOG_CFG_SESSION_DIR_CLEAR_FAIL": "[Settings] Failed to clear the session folder: {}",
    "LOG_CFG_ALL_DATA_CLEARED": "[Settings] All local data was reset.",
    "LOG_SES_SAVE_FAIL": "[Session] Failed to save session ('{}'): {}",
    "LOG_SES_LOAD_FAIL": "[Session] Failed to load session ('{}'): {}",
    "LOG_SES_DELETE_FAIL": "[Session] Failed to delete session ('{}'): {}",
    "LOG_SYS_STDERR_FLUSH_FAIL": "[System] Failed to flush the standard error stream: {}",
    "LOG_SYS_STARTUP_LOG_CLEANUP_FAIL": "[System] Failed to clean logs during startup: {}",
    "LOG_SYS_CLOSE_CLEANUP_FAIL": "[System] Failed to clean resources during shutdown: {}",
    "LOG_SYS_HANDLER_CLEANUP_FAIL": "[System] Cleanup handler error: {}",
    "LOG_SYS_CRITICAL_POPUP_FAIL": "[System] Failed to display the critical-error dialog: {}",
    "LOG_SYS_LOG_CLEANUP_FAILURE": "[System] Failed to clean log data: {}",
    "LOG_SES_LIST_FAIL": "[Session] Failed to retrieve the session list: {}",
    "LOG_CFG_SESSION_TITLE_READ_FAIL": "[Session] Failed to read the session title: {}",
    "LOG_CFG_SESSION_SEARCH_FAIL": "[Session] Error while searching session data: {}",
    "LOG_CFG_UNEXPECTED_LOAD_ERROR": "[Settings] Unexpected configuration loading error: {}",
    "LOG_CFG_BACKUP_CLEANUP_FAIL": "[Settings] Failed to remove the backup configuration: {}",
    "LOG_CFG_TEMP_REMOVE_FAIL": "[Settings] Failed to remove the temporary configuration: {}",
    "LOG_SES_TEMP_CLEANUP_FAIL": "[Session] Failed to clean temporary session data: {}",
    "LOG_CFG_LOG_FILE_CLEANUP_FAIL": "[Settings] Automatic log cleanup failed ('{}'): {}",
    "LOG_SCH_STARTED": "=== [Search] Starting task (initializing...) ===",
    "LOG_SCH_ERROR_START": "[Search] Initialization failed: {}",
    "LOG_SCH_COND_QUERY": "  └─ Search term: '{}'",
    "LOG_SCH_COND_FOLDER": "  └─ Target folder: {}",
    "LOG_SCH_COND_FILENAME": "  └─ Filename filter: '{}'",
    "LOG_SCH_COND_EXT": "  └─ Extension filter: '{}' (special mode: {})",
    "LOG_SCH_PATH_ENTER": "=== [Search] Engine started ===",
    "LOG_SCH_SCAN_DONE": "[Scan] Target files collected: '{}' ({:.3f}s).",
    "LOG_SCH_SCAN_DONE_WITH_SKIPPED": "[Scan] Target files collected: {} (skipped: {}, {:.3f}s).",
    "LOG_SCH_SCAN_DONE_SIMPLE": "[Scan] File scan completed ({:.3f}s).",
    "LOG_SCH_SCAN_STARTED_TYPE": "[Scan] Starting file scan ({})...",
    "LOG_SCH_SCAN_TYPE_RUST": "Rust fast path",
    "LOG_SCH_SCAN_TYPE_PYTHON": "Python deep path",
    "LOG_SCH_SKIPPED_FILES_LIST": "[Scan] Excluded search targets:",
    "LOG_SCH_SCAN_DONE_FAST_PATH": "[Scan] File scan completed (fast path).",
    "LOG_SCH_SEARCH_DONE": "=== [Search] Task completed (total: {:.3f}s) ===",
    "LOG_SCH_NO_FILES": "[Search] No files to search.",
    "LOG_SCH_EMPTY_QUERY": "[Search] No search term was entered.",
    "LOG_SCH_FOLDER_ACCESS_DENIED": "[Scan] Folder access denied: {} ({})",
    "LOG_SCH_SCAN_OS_ERROR": "[Scan] System I/O error: {} ({})",
    "LOG_SCH_RUST_MODE": "[Engine] Rust acceleration mode enabled.",
    "LOG_SCH_PYTHON_MODE": "[Engine] Python deep-search mode enabled.",
    "LOG_SCH_HYBRID_MODE": "[Engine] Hybrid mode (Rust + Python) enabled.",
    "LOG_SCH_STOP_REQUESTED": "[Control] Stop request received...",
    "LOG_SCH_STOPPED_BY_USER": "[Control] The task was stopped by the user.",
    "LOG_SCH_RESTART_PENDING": "[Control] Waiting to restart...",
    "LOG_SCH_RESTART_SCHEDULED": "[Control] Restart scheduled.",
    "LOG_SCH_SKIP_COUNT": "[Info] A total of {} files were excluded from the search.",
    "LOG_SCH_SKIP_REASON": "  └─ '{}' (reason: {})",
    "LOG_SCH_RETRY_PYTHON": "[Engine] Retrying automatically with the Python engine... ({})",
    "LOG_SCH_ALL_FILES_GUIDE": "[Info] Scanning all files.",
    "LOG_SCH_FILENAME_FILTER_GUIDE": "[Info] Filename filter applied: '{}'",
    "LOG_SCH_SMART_SCAN_SKIPPED": "[Scan] Smart scan bypassed: '{}' (reason: {})",
    "LOG_SCH_ALL_DONE": "=== [Search] All tasks finished. (total: {:.3f}s) ===",
    "LOG_WKR_STARTED": "[Engine] Starting parallel search processing ('{}' | filter: {} | {})",
    "LOG_WKR_RUNNING": "  └─ Processing: {} files...",
    "LOG_WKR_PROGRESS": "  └─ Search progress: {}% ({}/{})",
    "LOG_WKR_COMPLEX_ACT": "[Engine] Unicode deep-search mode (Python) enabled.",
    "LOG_WKR_PYTHON_ACT": "[Engine] Searching with the Python engine...",
    "LOG_WKR_RUST_ACT": "[Engine] Enabling the Rust engine (targets: {} paths).",
    "LOG_WKR_DONE": "[Engine] Parallel search completed (found: {}, matches: {}, {:.3f}s).",
    "LOG_WKR_EXCEL_SCAN": "[Engine] Excel structured-file search enabled.",
    "LOG_WKR_STOP_SIGNAL": "[Worker] Task stop signal detected.",
    "LOG_WKR_ADAPTIVE_POLICY_INFO": "[Worker] Adaptive resource policy: assigned {} workers from {} cores.",
    "LOG_RES_DATA_DIR_FAIL": "[Resource] Failed to open the data folder: {}",
    "LOG_RES_LOG_CLEANUP_FAIL": "[Resource] Failed to clean log data: {}",
    "LOG_PERF_MANAGER_INIT": "[Performance] Global multiprocessing manager initialized.",
    "LOG_PERF_MANAGER_FAIL": "[Performance] Failed to initialize manager: {}",
    "LOG_PERF_MANAGER_SHUTDOWN": "[Performance] Global multiprocessing manager shut down.",
    "LOG_EXECUTOR_SHUTDOWN_ERROR": "[Performance] Error while shutting down the executor: {}",
    "LOG_PERF_SKIP_RESIZE": "[Performance] Large data set ({} rows); skipping automatic column resizing.",
    "LOG_PERF_SKIP_MATCH_RESIZE": "[Performance] Large match set ({} rows); skipping detail-view auto-resize.",
    "LOG_PERF_ADJUST_MATCH_FAIL": "[Performance] Failed to adjust detail column widths: {}",
    "LOG_PERF_MANAGER_SHUTDOWN_ERROR": "[Performance] Error while shutting down the global manager: {}",
    "LOG_WKR_MANAGER_SHUTDOWN_IGNORED": "[Worker] Ignoring global manager shutdown (channel closed): {}",
    "LOG_WKR_SIGNAL_EMIT_FAIL": "[Worker] Failed to emit status signal ({}): {}",
    "LOG_WKR_FUTURE_SCHEDULING_SKIPPED": "[Worker] Task scheduling skipped (already stopped): {}",
    "LOG_WKR_FUTURE_SUBMISSION_FAIL": "[Worker] Failed to submit future: {}",
    "LOG_WKR_HANG_TIMEOUT": "[Worker] Batch response timed out ({}s); forcing termination.",
    "LOG_WKR_BATCH_FAILED": "[Worker] Batch execution failed: {}",
    "LOG_WKR_EXECUTOR_SHUTDOWN_ERROR": "[Worker] Failed to release executor resources: {}",
    "LOG_SYS_RUST_PATH": "[System] Loaded Rust engine path: {}",
    "LOG_SYS_RUST_HASH": "[System] Rust engine integrity check (SHA-256): {}",
    "LOG_SCH_RUST_PERF_STATS": "[Performance] Raw Rust statistics: Count={}, Call={:.4f}s, Norm={:.4f}s",
    "LOG_SCH_ENGINE_ISOLATION_BAIL": "[Engine] Task blocked by isolation policy (reason: {}): {}",
    "LOG_SCH_RUST_SMART_SCAN_FATAL": "[Error] A fatal exception occurred during smart scan: {}",
    "LOG_SCH_BINARY_COUNT_PARSE_FAIL": "[Engine] Failed to parse binary match count (length {}): {}",
    "LOG_SCH_EXISTENCE_DECODE_FAIL": "[Engine] Failed to decode during early existence check: {}",
    "LOG_SCH_EXISTENCE_JSON_FALLBACK": "[Engine] JSON existence check failed; using deep search for ('{}'): {}",
    "LOG_SCH_EXISTENCE_UNEXPECTED": "[Engine] Unexpected error during existence check ('{}'): {}",
    "LOG_SYS_RUST_NO_FALLBACK": "[System] Failed to load the Rust engine (Python fallback is disabled by policy).",
    "ERROR_TITLE": "Error",
    "ERROR_UNKNOWN": "Unknown system error.",
    "ERROR_UNEXPECTED_FILE": "[Error] Unexpected problem while processing file ('{}'): {}",
    "ERROR_JSON_PARSE": "[Error] Failed to parse JSON: {}",
    "ERROR_EXPORT_FAIL": "[Error] Failed to export results: {}",
    "ERROR_OPEN_DIR_FAILED": "[Error] Failed to open folder: {}",
    "ERROR_IO_DURING_SEARCH": "[Error] I/O error during search: {}",
    "ERROR_STOP_SEARCH_TAB": "[Error] Failed to stop the search tab: {}",
    "ERROR_EXCEL_ACCESS": "[Error] Failed to access Excel file: {}",
    "ERROR_EXCEL_SIGNATURE": "[Error] Invalid Excel file signature.",
    "ERROR_EXCEL_PROCESS": "[Error] Failed to convert Excel data: {}",
    "ERROR_EXCEL_CALAMINE": "[Error] The 'python-calamine' library required for Excel search is missing.",
    "ERROR_EXCEL_CALAMINE_REQ": "[Error] The 'python-calamine' library is required for Excel search.",
    "ERROR_EXCEL_LIB": "[Error] Excel library integration error: {}",
    "ERROR_SEARCH_EXCEL": "[Error] Integrated Excel search failed ('{}'): {}",
    "ERROR_SEARCH_EXCEL_SHEET": "[Error] Failed to search Excel sheet ('{}'): {}",
    "ERROR_EXCEL_PANIC": "[Error] A fatal Excel engine error occurred: {}",
    "EXCEL_DETAIL_RANGE_OUT_OF_BOUNDS": (
        "The {} worksheet data range is corrupted. Start index {} is outside the data length {}."
    ),
    "EXCEL_DETAIL_ENGINE_FAILURE": "An internal Excel engine error occurred while processing the {} file.",
    "EXCEL_DETAIL_UNKNOWN_FORMAT": "An internal Excel engine error occurred while processing the file.",
    "EXCEL_DETAIL_SHEET_FAILURE": "An internal Excel engine error occurred while reading worksheet data.",
    "ERROR_XML_PARSE": "[Error] Failed to parse XML: {}",
    "ERROR_XML_UNSUPPORTED_DTD": "[Info] XML DTD is not supported for safe parsing: {}",
    "XML_DETAIL_TAG_MISMATCH": "Closing tags do not match. Expected {}, but found {}.",
    "XML_DETAIL_MISMATCHED_TAG": "The opening and closing tags do not match.",
    "XML_DETAIL_DOCTYPE_POSITION": "The DOCTYPE declaration must appear before the root element.",
    "XML_DETAIL_DTD_UNSUPPORTED": "DTD declarations and entity expansion are not supported.",
    "XML_DETAIL_DECLARATION_POSITION": "The XML declaration must appear once at the beginning of the document.",
    "XML_DETAIL_MULTIPLE_ROOTS": "The document contains more than one root element.",
    "XML_DETAIL_UNEXPECTED_CLOSING": "A closing tag without a matching opening tag was found.",
    "XML_DETAIL_TEXT_OUTSIDE_ROOT": "Text exists outside the root element.",
    "XML_DETAIL_CDATA_OUTSIDE_ROOT": "CDATA exists outside the root element.",
    "XML_DETAIL_INCOMPLETE_DOCUMENT": "The XML document is incomplete or has no root element.",
    "XML_DETAIL_INVALID_ENCODING": "The XML character encoding is invalid.",
    "XML_DETAIL_INVALID_TOKEN": "An invalid XML token was found.",
    "XML_DETAIL_INVALID_ATTRIBUTE": "The XML attribute format is invalid.",
    "XML_DETAIL_INVALID_ENTITY": "The XML entity or escape sequence is invalid.",
    "XML_DETAIL_EMPTY_DOCTYPE": "The DOCTYPE declaration is empty.",
    "XML_DETAIL_UNKNOWN_NAMESPACE": "An undefined namespace prefix was used: {}",
    "XML_DETAIL_INVALID_DOCUMENT": "The XML document format is invalid.",
    "XML_DETAIL_WITH_POSITION": "{} (line {}, column {})",
    "JSON_DETAIL_INVALID_DOCUMENT": "The JSON document format is invalid.",
    "JSON_DETAIL_WITH_POSITION": "{} (line {}, column {})",
    "ERROR_FILE_ACCESS_BINARY": "[Error] Failed to determine whether the file is binary: {}",
    "ERROR_READ_FILE": "[Error] Failed to read file content ('{}'): {}",
    "ERROR_SEARCH_CRITICAL_MSG": "A critical error occurred during the search.\nCheck the Logs tab for details.\n\nCause: {}",
    "ERROR_SESSION_SAVE": "[Error] Failed to save session data: {}",
    "ERROR_LIMIT_REACHED": "[Info] Result threshold reached; search stopped for stability. (maximum: {})",
    "ERROR_MEMORY_CRITICAL": "[Info] Search was stopped to protect the system from memory exhaustion.",
    "ERROR_MEMORY_CRITICAL_TITLE": "Search stopped due to low memory",
    "ERROR_MEMORY_CRITICAL_DETAIL": (
        "Search was stopped because system memory usage is high.\n\n"
        "Close other applications and try again, or reduce the search scope and result limit."
    ),
    "TITLE_LIMIT_REACHED": "Search limit reached",
    "MSG_RESULT_LIMIT_REACHED": (
        "Search results exceeded the application limit (100,000), so the search was stopped immediately.\n"
        "Only results found so far are displayed."
    ),
    "MSG_MATCH_LIMIT_PER_FILE": "(Maximum matches per file reached: {})",
    "ERROR_NO_EXTENSION": "[Info] Select at least one extension to search.",
    "ERR_CRITICAL_SYSTEM": "[System] A critical internal application error occurred: {}",
    "LOG_SCH_BINARY_CHECK_FAIL": "[Error] Binary check failed ('{}'): {}",
    "LOG_SCH_UNEXPECTED_ERROR": "[Error] Unexpected application error ('{}' : {}): {}",
    "LOG_SCH_ERROR": "[Error] General search engine error: {}",
    "LOG_SCH_RUST_ENGINE_ERROR": "[Error] Rust core engine error ('{}'): {}",
    "LOG_SCH_RUST_JSON_FAIL": "[Error] Rust JSON search failed ('{}'): {}",
    "LOG_SCH_RUST_DIR_SEARCH_ERROR": "[Error] Rust directory traversal error ('{}'): {}",
    "LOG_SCH_JSON_LIMIT": "[Error] JSON object nesting limit exceeded.",
    "LOG_SCH_BINARY_CHECK_ERROR": "[Error] Binary integrity check failed: {}",
    "LOG_SCH_RUST_DIR_FATAL": "[Error] Fatal exception during Rust directory search ('{}'): {}",
    "LOG_SCH_RUST_FILELIST_FATAL": "[Error] Fatal exception while building the Rust file list ('{}'): {}",
    "LOG_SCH_RUST_SMART_SCAN_ERROR": "[Error] Rust smart-scan engine error ('{}'): {}",
    "LOG_SRCH_RUST_MEM_GUARD_WARN": "[Info] Rust engine memory guard activated: {}",
    "LOG_SCH_ERROR_FILE": "[Error] Failed to process file ('{}'): {}",
    "LOG_SCH_RUST_EXCEL_FAIL": "[Error] Rust Excel search failed ('{}'): {}",
    "LOG_SCH_JSON_FAIL": "[Error] Python JSON search failed: {}",
    "LOG_SCH_XML_FAIL": "[Error] Python XML search failed: {}",
    "LOG_SCH_RUST_XML_FAIL": "[Error] Rust XML search failed ('{}'): {}",
    "LOG_SCH_STREAM_ERROR": "[Error] Data stream processing was interrupted: {}",
    "LOG_SCH_STOP_THREAD_ERR": "[Error] Failed to stop worker thread: {}",
    "LOG_SCH_SEARCH_THREAD_ERROR": "[Error] Error received while closing search thread: {}",
    "LOG_SCH_EXCEL_SHEET_ERROR_DETAIL": "[Engine] Exception while parsing Excel sheet: {}",
    "LOG_SCH_EXCEL_ENGINE_PANIC_EXT": "[Engine] Excel core panic detected ('{}'): {}",
    "LOG_SCH_EXCEL_ENGINE_PANIC": "[Engine] Fatal Excel core panic: {}",
    "LOG_SCH_SKIP_RAW_DETAIL": "[Engine] Raw skipped-file diagnostic ({}): {}",
    "LOG_THEME_APPLY_FAIL": "[Display] Failed to apply visual theme (theme={}): {}",
    "ERROR_SORT_WORKER": "[Error] SortWorker failed: {}",
    "ERROR_GLOBAL_SORT_WORKER": "[Error] GlobalSortWorker error: {}",
    "LOG_WKR_BATCH_ERROR": "[Worker] Batch unit error: {}",
    "LOG_WORKER_ERROR_SIGNAL_FAIL": "[Worker] Failed to emit internal error signal.",
    "LOG_WORKER_FINISH_SIGNAL_FAIL": "[Worker] Failed to emit internal completion signal.",
    "LOG_QT_INFO": "[Qt] Information: {}",
    "LOG_QT_WARNING": "[Qt] Warning: {}",
    "LOG_QT_CRITICAL": "[Qt] Critical system error: {}",
    "LOG_QT_FATAL": "[Qt] Fatal process exception: {}",
    "SKIP_REASON_WALK": "[Error] Failed to traverse folder tree: {}",
    "SKIP_REASON_OPEN": "[Error] Permission denied while opening file: {}",
    "SKIP_REASON_METADATA": "[Error] Failed to read file metadata: {}",
    "SKIP_REASON_MMAP": "[Error] Failed to allocate memory map: {}",
    "SKIP_REASON_TOO_LARGE": "[Info] File size limit exceeded: {}",
    "SKIP_REASON_MEMORY_GUARD": "[Info] Engine memory guard activated: {}",
    "SKIP_REASON_JSON_SIZE_LIMIT": "[Info] JSON file size limit exceeded: {}",
    "SKIP_REASON_RESOURCE_BUDGET": "[Info] Insufficient file memory budget: {}",
    "SKIP_REASON_FILE_MATCH_LIMIT": "[Info] The per-file match limit ({}) was reached; later results were omitted.",
    "SKIP_REASON_JSON_DEPTH_LIMIT": "[Info] Nested content beyond the maximum JSON depth ({}) was not searched.",
    "SKIP_REASON_EXCEL_CELL_LIMIT": "[Info] The Excel existence-check cell limit ({}) was reached; later cells were not checked.",
    "SKIP_REASON_PANIC": "[Error] A lower-level engine panic occurred: {}",
    "SKIP_REASON_CRITICAL": "[Error] A critical exception was detected: {}",
    "SKIP_REASON_BATCH": "[Error] A file-processing batch failed: {}",
    "SKIP_REASON_UNKNOWN": "[Error] Skipped for an unknown reason: {}",
    "SKIP_DETAIL_PERMISSION_DENIED": "The operating system denied access.",
    "SKIP_DETAIL_FILE_NOT_FOUND": "The file or folder could not be found.",
    "SKIP_DETAIL_FILE_IN_USE": "The file is being used by another program.",
    "SKIP_DETAIL_PATH_TOO_LONG": "The file path exceeds the length allowed by the operating system.",
    "SKIP_DETAIL_IO_FAILURE": "File I/O processing failed.",
    "SKIP_DETAIL_INTERNAL_FAILURE": "An internal processing error occurred. See the logs for details.",
    "SKIP_DETAIL_LARGE_JSON": "Processing the large JSON document was stopped by the memory protection policy.",
    "SKIP_DETAIL_JSON_SIZE_LIMIT": "Structured JSON search was skipped for this file because it exceeds the configured maximum JSON parsing size.",
    "SKIP_DETAIL_RESOURCE_BUDGET": "Structured search was skipped for this file because its estimated processing memory would leave less than the system safety reserve.",
    "SKIP_DETAIL_FILE_SIZE_BYTES": "{} bytes",
    "SKIP_DETAIL_SIZE_LIMIT": "The file size exceeds the configured maximum.",
}
