[package]
name = "sf_engine"
version = "5.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.23.0", features = ["extension-module"] }
aho-corasick = "1.1"
memchr = "2.7"
memmap2 = "0.9.0"
encoding_rs = "0.8.33"
ignore = "0.4"
rayon = "1.8"
num_cpus = "1.16"
simdutf8 = "0.1"
calamine = { git = "https://github.com/tafia/calamine", branch = "master" }
crossbeam-channel = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
quick-xml = "0.31"
unicode-normalization = "0.1"
fs2 = "0.4"
globset = "0.4"
regex = "1.10"

[lib]
name = "sf_engine"
crate-type = ["cdylib"]

[profile.release]
lto = true
codegen-units = 1
panic = "unwind"
strip = true
opt-level = 3
